/**
 * Clinic source definitions for MedServicePrice.kz
 * =============================================================
 * Extracted from seed-data.ts to keep each module under Turbopack's
 * comfortable compilation budget. Re-exported by seed-data.ts for
 * backward compatibility.
 *
 * Contains:
 *  - ClinicSourceDef type (with optional parserType + sourceType)
 *  - CLINIC_SOURCES: 70 clinic source definitions across 14 KZ cities
 *    (24 curated chains with simulated scraping + 46 real public
 *    price-list sources with parserType "real_html")
 */

export type ClinicSourceDef = {
  sourceName: string;
  clinicName: string;
  city: string;
  address: string;
  phone: string;
  workingHours: string;
  sourceUrl: string;
  website: string;
  rating: number;
  onlineBooking: boolean;
  lat: number;
  lng: number;
  /**
   * Which registered scraper implementation should handle this source.
   * Defaults to "simulated" (the deterministic seed-data generator).
   * Set to "real_html" to have the RealHtmlScraper attempt a live fetch
   * with graceful fallback to simulated data on failure.
   */
  parserType?: string;
  /** Provenance tag for the admin UI (e.g. "103.kz pricing", "2GIS prices", "official pdf"). */
  sourceType?: string;
};

/** 68 clinic source definitions across 14 KZ cities. First 24 = curated chains (simulated); remaining 44 = real public price-list sources (real_html). */
export const CLINIC_SOURCES: ClinicSourceDef[] = [
  {
    sourceName: "KDL",
    clinicName: "Лаборатория KDL",
    city: "Алматы",
    address: "ул. Абылай хана, 38",
    phone: "+7 (727) 300-20-30",
    workingHours: "Пн–Сб 07:30–19:00, Вс 08:00–15:00",
    sourceUrl: "https://kdl.kz/almaty",
    website: "https://kdl.kz",
    rating: 4.6,
    onlineBooking: true,
    lat: 43.2389,
    lng: 76.8897,
  },
  {
    sourceName: "KDL",
    clinicName: "Лаборатория KDL",
    city: "Астана",
    address: "пр. Республики, 25",
    phone: "+7 (7172) 70-20-30",
    workingHours: "Пн–Сб 07:30–19:00, Вс 08:00–15:00",
    sourceUrl: "https://kdl.kz/astana",
    website: "https://kdl.kz",
    rating: 4.5,
    onlineBooking: true,
    lat: 51.1694,
    lng: 71.4491,
  },
  {
    sourceName: "Invitro",
    clinicName: "Лаборатория Инвитро",
    city: "Алматы",
    address: "пр. Достык, 132",
    phone: "+7 (727) 388-00-00",
    workingHours: "Ежедневно 07:00–20:00",
    sourceUrl: "https://invitro.kz/almaty",
    website: "https://invitro.kz",
    rating: 4.7,
    onlineBooking: true,
    lat: 43.2275,
    lng: 76.9519,
  },
  {
    sourceName: "Invitro",
    clinicName: "Лаборатория Инвитро",
    city: "Шымкент",
    address: "ул. Толе би, 12",
    phone: "+7 (7252) 50-00-00",
    workingHours: "Ежедневно 07:00–20:00",
    sourceUrl: "https://invitro.kz/shymkent",
    website: "https://invitro.kz",
    rating: 4.5,
    onlineBooking: true,
    lat: 42.3433,
    lng: 69.5893,
  },
  {
    sourceName: "Olymp",
    clinicName: "Медцентр Олимп",
    city: "Алматы",
    address: "ул. Тимирязева, 42",
    phone: "+7 (727) 355-50-50",
    workingHours: "Пн–Пт 08:00–20:00, Сб 09:00–17:00",
    sourceUrl: "https://olymp.kz/almaty",
    website: "https://olymp.kz",
    rating: 4.4,
    onlineBooking: true,
    lat: 43.2401,
    lng: 76.9289,
  },
  {
    sourceName: "Olymp",
    clinicName: "Медцентр Олимп",
    city: "Астана",
    address: "ул. Кенесары, 67",
    phone: "+7 (7172) 55-50-50",
    workingHours: "Пн–Пт 08:00–20:00, Сб 09:00–17:00",
    sourceUrl: "https://olymp.kz/astana",
    website: "https://olymp.kz",
    rating: 4.3,
    onlineBooking: true,
    lat: 51.1801,
    lng: 71.4189,
  },
  {
    sourceName: "Helix",
    clinicName: "Лаборатория Хеликс",
    city: "Караганда",
    address: "пр. Бухар жырау, 49",
    phone: "+7 (7212) 90-20-20",
    workingHours: "Пн–Сб 07:30–19:00",
    sourceUrl: "https://helix.kz/karaganda",
    website: "https://helix.kz",
    rating: 4.2,
    onlineBooking: false,
    lat: 49.8101,
    lng: 73.1151,
  },
  {
    sourceName: "Helix",
    clinicName: "Лаборатория Хеликс",
    city: "Павлодар",
    address: "ул. Ломова, 11",
    phone: "+7 (7182) 70-20-20",
    workingHours: "Пн–Сб 07:30–19:00",
    sourceUrl: "https://helix.kz/pavlodar",
    website: "https://helix.kz",
    rating: 4.1,
    onlineBooking: false,
    lat: 52.2921,
    lng: 76.9701,
  },
  {
    sourceName: "Medel",
    clinicName: "Клиника МЕДЭЛ",
    city: "Алматы",
    address: "ул. Макатаева, 117",
    phone: "+7 (727) 333-30-30",
    workingHours: "Круглосуточно",
    sourceUrl: "https://medel.kz",
    website: "https://medel.kz",
    rating: 4.5,
    onlineBooking: true,
    lat: 43.2612,
    lng: 76.8912,
  },
  {
    sourceName: "Medel",
    clinicName: "Клиника МЕДЭЛ",
    city: "Актобе",
    address: "пр. Абылхайыр хана, 42",
    phone: "+7 (7132) 90-30-30",
    workingHours: "Круглосуточно",
    sourceUrl: "https://medel.kz/aktobe",
    website: "https://medel.kz",
    rating: 4.4,
    onlineBooking: true,
    lat: 50.2901,
    lng: 57.1601,
  },
  {
    sourceName: "AksaiClinic",
    clinicName: "Аксайская клиника",
    city: "Атырау",
    address: "пр. Сатпаева, 14",
    phone: "+7 (7122) 35-15-15",
    workingHours: "Пн–Пт 08:00–18:00",
    sourceUrl: "https://aksai-clinic.kz",
    website: "https://aksai-clinic.kz",
    rating: 4.0,
    onlineBooking: false,
    lat: 47.1201,
    lng: 51.8801,
  },
  {
    sourceName: "MCK",
    clinicName: "Медицинский центр МЦК",
    city: "Семей",
    address: "ул. Абая, 156",
    phone: "+7 (7222) 52-22-22",
    workingHours: "Пн–Сб 08:00–19:00",
    sourceUrl: "https://mck.kz",
    website: "https://mck.kz",
    rating: 4.3,
    onlineBooking: true,
    lat: 50.4201,
    lng: 80.2201,
  },
  {
    sourceName: "OnClinic",
    clinicName: "Клиника Он Клиник",
    city: "Алматы",
    address: "пр. Абая, 88",
    phone: "+7 (727) 344-44-44",
    workingHours: "Пн–Сб 08:00–20:00, Вс 09:00–17:00",
    sourceUrl: "https://onclinic.kz/almaty",
    website: "https://onclinic.kz",
    rating: 4.4,
    onlineBooking: true,
    lat: 43.2567,
    lng: 76.9286,
  },
  {
    sourceName: "SultanZharbulov",
    clinicName: "Клиника Султана Жарбулова",
    city: "Астана",
    address: "ул. Бейбитшилик, 21",
    phone: "+7 (7172) 47-77-77",
    workingHours: "Пн–Пт 08:00–20:00, Сб 09:00–16:00",
    sourceUrl: "https://sultan-clinic.kz/astana",
    website: "https://sultan-clinic.kz",
    rating: 4.5,
    onlineBooking: true,
    lat: 51.1234,
    lng: 71.4309,
  },
  {
    sourceName: "GreenClinic",
    clinicName: "Грин Клиник",
    city: "Шымкент",
    address: "пр. Республики, 15",
    phone: "+7 (7252) 40-10-10",
    workingHours: "Пн–Сб 07:30–19:30, Вс 09:00–15:00",
    sourceUrl: "https://greenclinic.kz/shymkent",
    website: "https://greenclinic.kz",
    rating: 4.2,
    onlineBooking: false,
    lat: 42.3456,
    lng: 69.5945,
  },
  {
    sourceName: "Medilux",
    clinicName: "Медицинский центр Медилux",
    city: "Караганда",
    address: "ул. Ерубаева, 33",
    phone: "+7 (7212) 99-88-77",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://medilux.kz/karaganda",
    website: "https://medilux.kz",
    rating: 4.1,
    onlineBooking: true,
    lat: 49.8234,
    lng: 73.1656,
  },
  {
    sourceName: "Medicus",
    clinicName: "Медицинский центр Медикус",
    city: "Алматы",
    address: "ул. Тимирязева, 38",
    phone: "+7 (727) 311-22-33",
    workingHours: "Пн–Сб 08:00–20:00, Вс 09:00–15:00",
    sourceUrl: "https://medicus.kz/almaty",
    website: "https://medicus.kz",
    rating: 4.3,
    onlineBooking: true,
    lat: 43.2385,
    lng: 76.948,
  },
  {
    sourceName: "Medicus",
    clinicName: "Медицинский центр Медикус",
    city: "Астана",
    address: "ул. Бокейханова, 19",
    phone: "+7 (7172) 36-22-33",
    workingHours: "Пн–Сб 08:00–20:00, Вс 09:00–15:00",
    sourceUrl: "https://medicus.kz/astana",
    website: "https://medicus.kz",
    rating: 4.2,
    onlineBooking: true,
    lat: 51.1727,
    lng: 71.426,
  },
  {
    sourceName: "SferaZdorovya",
    clinicName: "Клиника Сфера Здоровья",
    city: "Шымкент",
    address: "ул. Желтоксан, 25",
    phone: "+7 (7252) 55-33-22",
    workingHours: "Пн–Пт 08:00–19:00, Сб 09:00–16:00",
    sourceUrl: "https://sfera-zdorovya.kz/shymkent",
    website: "https://sfera-zdorovya.kz",
    rating: 4.0,
    onlineBooking: false,
    lat: 42.342,
    lng: 69.59,
  },
  {
    sourceName: "DalaMed",
    clinicName: "Медицинский центр Дала Мед",
    city: "Актобе",
    address: "пр. Абилкайыр хана, 76",
    phone: "+7 (7132) 50-20-20",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://dala-med.kz/aktobe",
    website: "https://dala-med.kz",
    rating: 4.1,
    onlineBooking: true,
    lat: 50.295,
    lng: 57.165,
  },
  {
    sourceName: "Beibalaife",
    clinicName: "Перинатальный центр Бэйбилайф",
    city: "Алматы",
    address: "ул. Розыбакиева, 261",
    phone: "+7 (727) 393-30-30",
    workingHours: "Круглосуточно",
    sourceUrl: "https://beibalaife.kz",
    website: "https://beibalaife.kz",
    rating: 4.6,
    onlineBooking: true,
    lat: 43.218,
    lng: 76.892,
  },
  {
    sourceName: "Medison",
    clinicName: "Медицинский центр MEDISON",
    city: "Павлодар",
    address: "ул. Ленина, 56",
    phone: "+7 (7182) 33-44-55",
    workingHours: "Пн–Сб 08:00–19:00",
    sourceUrl: "https://medison.kz/pavlodar",
    website: "https://medison.kz",
    rating: 4.0,
    onlineBooking: false,
    lat: 52.287,
    lng: 76.97,
  },
  {
    sourceName: "Essen",
    clinicName: "Клиника Эссен",
    city: "Караганда",
    address: "ул. Алиханова, 12",
    phone: "+7 (7212) 44-55-66",
    workingHours: "Пн–Сб 08:00–20:00, Вс 09:00–14:00",
    sourceUrl: "https://essen-clinic.kz/karaganda",
    website: "https://essen-clinic.kz",
    rating: 4.2,
    onlineBooking: true,
    lat: 49.812,
    lng: 73.108,
  },
  {
    sourceName: "RakhatMed",
    clinicName: "Медицинский центр Рахат Мед",
    city: "Атырау",
    address: "пр. Казахстан, 38",
    phone: "+7 (7122) 60-70-80",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://rakhat-med.kz/atyrau",
    website: "https://rakhat-med.kz",
    rating: 4.1,
    onlineBooking: true,
    lat: 47.118,
    lng: 51.88,
  },

  // ---- Extended real KZ sources (103.kz, 2GIS, official pages/PDFs) ----
  // Extracted from curated public price-list research. Each entry maps a real
  // Kazakhstan clinic to its city; parserType "real_html" instructs the worker
  // to attempt a live fetch via RealHtmlScraper (with graceful fallback).
  {
    sourceName: "NeironClinic",
    clinicName: "Neiron Clinic",
    city: "Актау",
    address: "г. Актау",
    phone: "+7 (700) 000-00-00",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://neironclinic.kz/wp-content/uploads/2025/07/novyj-prejskurant-2025.pdf",
    website: "https://neironclinic.kz",
    rating: 4.0,
    onlineBooking: false,
    lat: 43.6551,
    lng: 51.1594,
    parserType: "real_html",
    sourceType: "official pdf",
  },
  {
    sourceName: "AktobeMC",
    clinicName: "Актюбинский областной медицинский центр",
    city: "Актобе",
    address: "г. Актобе",
    phone: "+7 (7132) 50-00-00",
    workingHours: "Пн–Пт 08:00–18:00",
    sourceUrl: "https://aktobemc.kz/preyskurant-cen-za-2025g.html",
    website: "https://aktobemc.kz",
    rating: 4.1,
    onlineBooking: false,
    lat: 50.2839,
    lng: 57.167,
    parserType: "real_html",
    sourceType: "official page",
  },
  {
    sourceName: "DaruClinic",
    clinicName: "Клиника Дару",
    city: "Актобе",
    address: "г. Актобе",
    phone: "+7 (7132) 40-00-00",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://daru-clinic.kz/files/price.pdf",
    website: "https://daru-clinic.kz",
    rating: 4.2,
    onlineBooking: true,
    lat: 50.295,
    lng: 57.165,
    parserType: "real_html",
    sourceType: "official pdf",
  },
  {
    sourceName: "DostarMed",
    clinicName: "DostarMed",
    city: "Алматы",
    address: "г. Алматы",
    phone: "+7 (727) 300-00-00",
    workingHours: "Круглосуточно",
    sourceUrl: "https://dostar-med-2.103.kz/pricing/156/66516/",
    website: "https://dostar-med-2.103.kz",
    rating: 4.3,
    onlineBooking: true,
    lat: 43.25,
    lng: 76.92,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "SanaVita",
    clinicName: "Sana Vita Medical",
    city: "Алматы",
    address: "г. Алматы",
    phone: "+7 (727) 300-00-01",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://sanavita.103.kz/pricing/",
    website: "https://sanavita.103.kz",
    rating: 4.4,
    onlineBooking: true,
    lat: 43.24,
    lng: 76.91,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "AvestaClinic",
    clinicName: "Авеста",
    city: "Алматы",
    address: "г. Алматы",
    phone: "+7 (727) 300-00-02",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://avesta.103.kz/pricing/",
    website: "https://avesta.103.kz",
    rating: 4.0,
    onlineBooking: false,
    lat: 43.26,
    lng: 76.93,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "AkademiaZdorovya",
    clinicName: "Академия Здоровья",
    city: "Алматы",
    address: "г. Алматы",
    phone: "+7 (727) 300-00-03",
    workingHours: "Пн–Сб 07:30–19:00",
    sourceUrl: "https://akademija-zdorovyja.103.kz/pricing/",
    website: "https://akademija-zdorovyja.103.kz",
    rating: 4.2,
    onlineBooking: true,
    lat: 43.23,
    lng: 76.94,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "DauletCenter",
    clinicName: "Даулет-Центр",
    city: "Алматы",
    address: "г. Алматы",
    phone: "+7 (727) 300-00-04",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://daulet-centr-1.103.kz/pricing/",
    website: "https://daulet-centr-1.103.kz",
    rating: 4.3,
    onlineBooking: true,
    lat: 43.22,
    lng: 76.90,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "Emirmed",
    clinicName: "Медицинский центр Эмирмед",
    city: "Алматы",
    address: "г. Алматы",
    phone: "+7 (727) 300-00-05",
    workingHours: "Круглосуточно",
    sourceUrl: "https://emirmed.103.kz/pricing/33/21730/",
    website: "https://emirmed.103.kz",
    rating: 4.1,
    onlineBooking: true,
    lat: 43.27,
    lng: 76.95,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "NurLabAlm",
    clinicName: "НурЛаб",
    city: "Алматы",
    address: "г. Алматы",
    phone: "+7 (727) 300-00-06",
    workingHours: "Пн–Сб 07:30–19:00",
    sourceUrl: "https://nurlab.103.kz/pricing/5135/111531/",
    website: "https://nurlab.103.kz",
    rating: 4.5,
    onlineBooking: true,
    lat: 43.24,
    lng: 76.88,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "SunkarRazv",
    clinicName: "Сункар на Развилке",
    city: "Алматы",
    address: "г. Алматы",
    phone: "+7 (727) 300-00-07",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://sunkar-2.103.kz/pricing/175/16318/",
    website: "https://sunkar-2.103.kz",
    rating: 4.0,
    onlineBooking: false,
    lat: 43.21,
    lng: 76.89,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "TsentralnayaSemey",
    clinicName: "Центральная семейная клиника",
    city: "Алматы",
    address: "г. Алматы",
    phone: "+7 (727) 300-00-08",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://semeinaya-klinika.103.kz/pricing/",
    website: "https://semeinaya-klinika.103.kz",
    rating: 4.2,
    onlineBooking: true,
    lat: 43.25,
    lng: 76.91,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "AdiyaMed",
    clinicName: "Adiya Medical Group",
    city: "Алматы",
    address: "г. Алматы",
    phone: "+7 (727) 300-00-09",
    workingHours: "Пн–Сб 09:00–18:00",
    sourceUrl: "https://2gis.kz/almaty/firm/70000001085351028/tab/prices",
    website: "https://2gis.kz",
    rating: 4.3,
    onlineBooking: false,
    lat: 43.26,
    lng: 76.92,
    parserType: "real_html",
    sourceType: "2GIS prices",
  },
  {
    sourceName: "KoreanMedCenter",
    clinicName: "Korean Medical Center",
    city: "Алматы",
    address: "г. Алматы",
    phone: "+7 (727) 300-00-10",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://2gis.kz/almaty/firm/70000001101364328/tab/prices",
    website: "https://2gis.kz",
    rating: 4.6,
    onlineBooking: true,
    lat: 43.24,
    lng: 76.93,
    parserType: "real_html",
    sourceType: "2GIS prices",
  },
  {
    sourceName: "GP19",
    clinicName: "Городская поликлиника №19",
    city: "Алматы",
    address: "г. Алматы",
    phone: "+7 (727) 300-00-11",
    workingHours: "Пн–Пт 08:00–18:00",
    sourceUrl: "https://gp19.kz/prejskurant/",
    website: "https://gp19.kz",
    rating: 3.9,
    onlineBooking: false,
    lat: 43.23,
    lng: 76.90,
    parserType: "real_html",
    sourceType: "official page",
  },
  {
    sourceName: "GP21",
    clinicName: "Городская поликлиника №21",
    city: "Алматы",
    address: "г. Алматы",
    phone: "+7 (727) 300-00-12",
    workingHours: "Пн–Пт 08:00–18:00",
    sourceUrl: "https://www.gp21.kz/page.php?n=pou",
    website: "https://www.gp21.kz",
    rating: 3.8,
    onlineBooking: false,
    lat: 43.22,
    lng: 76.91,
    parserType: "real_html",
    sourceType: "official page",
  },
  {
    sourceName: "FamilyClinicAst",
    clinicName: "Family Clinic",
    city: "Астана",
    address: "г. Астана",
    phone: "+7 (7172) 50-00-01",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://family-clinic.103.kz/pricing/6010/102258/",
    website: "https://family-clinic.103.kz",
    rating: 4.2,
    onlineBooking: true,
    lat: 51.17,
    lng: 71.43,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "MUAast",
    clinicName: "MUA medical center",
    city: "Астана",
    address: "г. Астана",
    phone: "+7 (7172) 50-00-02",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://mua.103.kz/pricing/",
    website: "https://mua.103.kz",
    rating: 4.1,
    onlineBooking: true,
    lat: 51.16,
    lng: 71.44,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "BMCUDP",
    clinicName: "БМЦ УДП РК",
    city: "Астана",
    address: "г. Астана",
    phone: "+7 (7172) 50-00-03",
    workingHours: "Пн–Пт 08:00–18:00",
    sourceUrl: "https://bmcudpkz.103.kz/pricing/",
    website: "https://bmcudp.kz",
    rating: 4.4,
    onlineBooking: true,
    lat: 51.18,
    lng: 71.42,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "LuchAst",
    clinicName: "Луч медицинский центр",
    city: "Астана",
    address: "г. Астана",
    phone: "+7 (7172) 50-00-04",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://lych.103.kz/pricing/",
    website: "https://lych.103.kz",
    rating: 4.0,
    onlineBooking: false,
    lat: 51.15,
    lng: 71.45,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "EcoLifeAst",
    clinicName: "Медицинский центр Эколайф",
    city: "Астана",
    address: "г. Астана",
    phone: "+7 (7172) 50-00-05",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://astana-ekolajf.103.kz/pricing/376/109303/",
    website: "https://astana-ekolajf.103.kz",
    rating: 4.1,
    onlineBooking: true,
    lat: 51.16,
    lng: 71.46,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "LucemAst",
    clinicName: "Lucem medical clinic",
    city: "Астана",
    address: "г. Астана",
    phone: "+7 (7172) 50-00-06",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://2gis.kz/astana/firm/70000001037651642/tab/prices",
    website: "https://2gis.kz",
    rating: 4.3,
    onlineBooking: true,
    lat: 51.17,
    lng: 71.44,
    parserType: "real_html",
    sourceType: "2GIS prices",
  },
  {
    sourceName: "ElAmanAst",
    clinicName: "Medical Clinic El Aman",
    city: "Астана",
    address: "г. Астана",
    phone: "+7 (7172) 50-00-07",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://2gis.kz/astana/firm/70000001081289519/tab/prices",
    website: "https://2gis.kz",
    rating: 4.2,
    onlineBooking: true,
    lat: 51.18,
    lng: 71.43,
    parserType: "real_html",
    sourceType: "2GIS prices",
  },
  {
    sourceName: "MedGardenAst",
    clinicName: "Medical Garden",
    city: "Астана",
    address: "г. Астана",
    phone: "+7 (7172) 50-00-08",
    workingHours: "Пн–Сб 07:30–19:30",
    sourceUrl: "https://2gis.kz/astana/firm/70000001079049028/tab/prices",
    website: "https://2gis.kz",
    rating: 4.0,
    onlineBooking: false,
    lat: 51.16,
    lng: 71.45,
    parserType: "real_html",
    sourceType: "2GIS prices",
  },
  {
    sourceName: "NaonAst",
    clinicName: "Научно-национальный медицинский центр",
    city: "Астана",
    address: "г. Астана",
    phone: "+7 (7172) 50-00-09",
    workingHours: "Пн–Пт 08:00–18:00",
    sourceUrl: "https://naoncgt.kz/?page_id=771",
    website: "https://naoncgt.kz",
    rating: 4.5,
    onlineBooking: true,
    lat: 51.18,
    lng: 71.42,
    parserType: "real_html",
    sourceType: "official site",
  },
  {
    sourceName: "GP11Ast",
    clinicName: "Городская поликлиника №11",
    city: "Астана",
    address: "г. Астана",
    phone: "+7 (7172) 50-00-10",
    workingHours: "Пн–Пт 08:00–18:00",
    sourceUrl: "https://www.emhana11.kz/",
    website: "https://www.emhana11.kz",
    rating: 3.7,
    onlineBooking: false,
    lat: 51.15,
    lng: 71.44,
    parserType: "real_html",
    sourceType: "official page",
  },
  {
    sourceName: "UMC_Ast",
    clinicName: "Медицинский центр UMC",
    city: "Астана",
    address: "г. Астана",
    phone: "+7 (7172) 50-00-11",
    workingHours: "Пн–Пт 08:00–18:00",
    sourceUrl: "https://umc.org.kz/wp-content/uploads/2019/11/prejskurant-czen-na-platnye-mediczinskie-uslugi-kf-umc.pdf",
    website: "https://umc.org.kz",
    rating: 4.4,
    onlineBooking: true,
    lat: 51.19,
    lng: 71.41,
    parserType: "real_html",
    sourceType: "official pdf",
  },
  {
    sourceName: "AldiMedKrg",
    clinicName: "ALDIMED",
    city: "Караганда",
    address: "г. Караганда",
    phone: "+7 (7212) 50-00-01",
    workingHours: "Пн–Сб 07:30–19:00",
    sourceUrl: "https://aldi-med.103.kz/pricing/",
    website: "https://aldi-med.103.kz",
    rating: 4.3,
    onlineBooking: true,
    lat: 49.81,
    lng: 73.11,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "AvicennaKrg",
    clinicName: "Авиценна",
    city: "Караганда",
    address: "г. Караганда",
    phone: "+7 (7212) 50-00-02",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://avicenna-4.103.kz/pricing/1455/40664/",
    website: "https://avicenna-4.103.kz",
    rating: 4.1,
    onlineBooking: false,
    lat: 49.82,
    lng: 73.10,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "AlyaMedShym",
    clinicName: "ALYA MED",
    city: "Шымкент",
    address: "г. Шымкент",
    phone: "+7 (7252) 50-00-01",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://alya-med.103.kz/pricing/",
    website: "https://alya-med.103.kz",
    rating: 4.2,
    onlineBooking: true,
    lat: 42.34,
    lng: 69.59,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "BestMedShym",
    clinicName: "BestMed Clinic",
    city: "Шымкент",
    address: "г. Шымкент",
    phone: "+7 (7252) 50-00-02",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://bestmedclinic.103.kz/pricing/",
    website: "https://bestmedclinic.103.kz",
    rating: 4.3,
    onlineBooking: true,
    lat: 42.35,
    lng: 69.58,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "InterteachShym",
    clinicName: "Interteach",
    city: "Шымкент",
    address: "г. Шымкент",
    phone: "+7 (7252) 50-00-03",
    workingHours: "Круглосуточно",
    sourceUrl: "https://intertich.103.kz/pricing/1129/112148/",
    website: "https://intertich.103.kz",
    rating: 4.0,
    onlineBooking: true,
    lat: 42.33,
    lng: 69.60,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "JakMedShym",
    clinicName: "JAK-MED",
    city: "Шымкент",
    address: "г. Шымкент",
    phone: "+7 (7252) 50-00-04",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://jak-med.103.kz/pricing/",
    website: "https://jak-med.103.kz",
    rating: 4.1,
    onlineBooking: false,
    lat: 42.34,
    lng: 69.59,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "MereiMedShym",
    clinicName: "MereiMed",
    city: "Шымкент",
    address: "г. Шымкент",
    phone: "+7 (7252) 50-00-05",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://mereimed.103.kz/pricing/1190/8541/",
    website: "https://mereimed.103.kz",
    rating: 4.2,
    onlineBooking: true,
    lat: 42.35,
    lng: 69.59,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "ShymMedServ",
    clinicName: "Shymkent Medical Services",
    city: "Шымкент",
    address: "г. Шымкент",
    phone: "+7 (7252) 50-00-06",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://shmedserv.103.kz/pricing/",
    website: "https://shmedserv.103.kz",
    rating: 4.3,
    onlineBooking: true,
    lat: 42.33,
    lng: 69.58,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "SanMedShym",
    clinicName: "Сан-Мед Сервис",
    city: "Шымкент",
    address: "г. Шымкент",
    phone: "+7 (7252) 50-00-07",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://sanmed-servis.103.kz/pricing/",
    website: "https://sanmed-servis.103.kz",
    rating: 4.0,
    onlineBooking: false,
    lat: 42.34,
    lng: 69.60,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "ShapagatShym",
    clinicName: "Шапағат",
    city: "Шымкент",
    address: "г. Шымкент",
    phone: "+7 (7252) 50-00-08",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://shapagat1.103.kz/pricing/",
    website: "https://shapagat1.103.kz",
    rating: 4.1,
    onlineBooking: false,
    lat: 42.35,
    lng: 69.60,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "AsylzhanShym",
    clinicName: "Asylzhan Medical",
    city: "Шымкент",
    address: "г. Шымкент",
    phone: "+7 (7252) 50-00-09",
    workingHours: "Пн–Сб 09:00–18:00",
    sourceUrl: "https://2gis.kz/shymkent/firm/70000001076228710/tab/prices",
    website: "https://2gis.kz",
    rating: 4.2,
    onlineBooking: false,
    lat: 42.33,
    lng: 69.59,
    parserType: "real_html",
    sourceType: "2GIS prices",
  },
  {
    sourceName: "DensaulykSemey",
    clinicName: "Денсаулық Семей",
    city: "Семей",
    address: "г. Семей",
    phone: "+7 (7222) 50-00-01",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://densaulyksemey.kz/wp-content/uploads/2020/02/%D0%BF%D1%80%D0%B5%D0%B9%D1%81%D0%BA%D1%83%D1%80%D0%B0%D0%BD%D1%82-%D0%94%D0%B5%D0%BD%D1%81%D0%B0%D1%83%D0%BB%D1%8B%D2%9B.pdf",
    website: "https://densaulyksemey.kz",
    rating: 4.0,
    onlineBooking: false,
    lat: 50.41,
    lng: 80.22,
    parserType: "real_html",
    sourceType: "official pdf",
  },
  {
    sourceName: "FreseniusKst",
    clinicName: "Fresenius Medical Care",
    city: "Костанай",
    address: "г. Костанай",
    phone: "+7 (7142) 50-00-01",
    workingHours: "Круглосуточно",
    sourceUrl: "https://frezenius-medikal-keyr-kazahstan-4.103.kz/pricing/",
    website: "https://www.freseniusmedicalcare.kz",
    rating: 4.4,
    onlineBooking: false,
    lat: 53.21,
    lng: 63.63,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "FreseniusUst",
    clinicName: "Fresenius Medical Care",
    city: "Усть-Каменогорск",
    address: "г. Усть-Каменогорск",
    phone: "+7 (7232) 50-00-01",
    workingHours: "Круглосуточно",
    sourceUrl: "https://frezenius-medikal-keyr-kazahstan-7.103.kz/pricing/search/5609/",
    website: "https://www.freseniusmedicalcare.kz",
    rating: 4.3,
    onlineBooking: false,
    lat: 49.97,
    lng: 82.60,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "FreseniusAlm",
    clinicName: "Fresenius Medical Care",
    city: "Алматы",
    address: "г. Алматы",
    phone: "+7 (727) 300-00-20",
    workingHours: "Круглосуточно",
    sourceUrl: "https://frezenius-medikal-keyr-kazahstan-1.103.kz/pricing/",
    website: "https://www.freseniusmedicalcare.kz",
    rating: 4.5,
    onlineBooking: false,
    lat: 43.25,
    lng: 76.92,
    parserType: "real_html",
    sourceType: "103.kz pricing",
  },
  {
    sourceName: "GP3SKO",
    clinicName: "Городская поликлиника №3 СКО",
    city: "Петропавловск",
    address: "г. Петропавловск",
    phone: "+7 (7152) 50-00-01",
    workingHours: "Пн–Пт 08:00–18:00",
    sourceUrl: "https://poliklinika.sko.kz/ru/%D1%83%D1%81%D0%BB%D1%83%D0%B3%D0%B8-%D0%B8-%D1%86%D0%B5%D0%BD%D1%8B.html",
    website: "https://poliklinika.sko.kz",
    rating: 3.9,
    onlineBooking: false,
    lat: 54.88,
    lng: 69.17,
    parserType: "real_html",
    sourceType: "official page",
  },
  {
    sourceName: "GioTrade",
    clinicName: "GIO TRADE медицинский центр",
    city: "Алматы",
    address: "г. Алматы",
    phone: "+7 (727) 300-00-30",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://www.giomed.kz/gallery/%D0%BD%D0%BE%D0%B2%D1%8B%D0%B9%20%D0%BF%D1%80%D0%B5%D0%B9%D1%81%D0%BA%D1%83%D1%80%D0%B0%D0%BD%D1%82%20%D1%86%D0%B5%D0%BD%20%202025.pdf",
    website: "https://www.giomed.kz",
    rating: 4.1,
    onlineBooking: true,
    lat: 43.25,
    lng: 76.90,
    parserType: "real_html",
    sourceType: "official pdf",
  },
  {
    sourceName: "GreenMedAlm",
    clinicName: "Green Medical",
    city: "Алматы",
    address: "г. Алматы",
    phone: "+7 (727) 300-00-31",
    workingHours: "Пн–Сб 09:00–18:00",
    sourceUrl: "https://2gis.kz/almaty/firm/70000001066229914/tab/prices",
    website: "https://2gis.kz",
    rating: 4.0,
    onlineBooking: false,
    lat: 43.24,
    lng: 76.91,
    parserType: "real_html",
    sourceType: "2GIS prices",
  },
  {
    sourceName: "NurLab2GIS",
    clinicName: "NurLab medical clinic",
    city: "Алматы",
    address: "г. Алматы",
    phone: "+7 (727) 300-00-32",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://2gis.kz/almaty/firm/70000001111673619/tab/prices",
    website: "https://2gis.kz",
    rating: 4.4,
    onlineBooking: true,
    lat: 43.23,
    lng: 76.92,
    parserType: "real_html",
    sourceType: "2GIS prices",
  },
];
