/**
 * Seed data for MedServicePrice.kz
 * -------------------------------------------------------------
 * - 120 normalized medical services across 4 categories (laboratory, doctor_appointment, diagnostics, procedure)
 *   Each entry has RU/KK/EN names + synonyms covering common abbreviations (ОАК, CBC, etc.)
 * - 24 clinic source definitions (KDL, Invitro, Olymp, Helix, Medicus, Сфера Здоровья, Дала Мед, Бэйбилайф,
 *   MEDISON, Эссен, Рахат Мед, etc.) across major KZ cities with real geo-coordinates for Leaflet mapping.
 * - Raw payload generators that simulate 3 scraper sources producing realistic price lists
 *   including synonym variations of service names (so the normalization engine has real work to do).
 */

export type ServiceCategory = "laboratory" | "doctor_appointment" | "diagnostics" | "procedure";

export type ServiceSeed = {
  nameRu: string;
  nameKk: string;
  nameEn: string;
  synonyms: string[];
  category: ServiceCategory;
  description: string;
  unit?: string;
};

/** 120 normalized medical reference services (RU/KK/EN names + synonyms). */
export const SERVICE_DIRECTORY_SEED: ServiceSeed[] = [
  // ---- Laboratory (22) ----
  {
    nameRu: "Общий анализ крови (ОАК)",
    nameKk: "Жалпы қан талдауы (ЖАҚ)",
    nameEn: "Complete Blood Count (CBC)",
    synonyms: ["ОАК", "CBC", "Клинический анализ крови", "Общий анализ крови", "ЖАҚ", "general blood test", "blood count", "UAC"],
    category: "laboratory",
    description: "Базовое исследование показателей крови: гемоглобин, лейкоциты, тромбоциты, СОЭ.",
    unit: "шт",
  },
  {
    nameRu: "Общий анализ мочи",
    nameKk: "Жалпы зәр талдауы",
    nameEn: "Urinalysis",
    synonyms: ["ОАМ", "анализ мочи", "urine test", "general urine analysis", "ОАМ"],
    category: "laboratory",
    description: "Физико-химическое исследование мочи.",
    unit: "шт",
  },
  {
    nameRu: "Биохимический анализ крови",
    nameKk: "Қанның биохимиялық талдауы",
    nameEn: "Comprehensive Metabolic Panel",
    synonyms: ["биохимия крови", "biochemistry", "LHC", "БХК", "metabolic panel"],
    category: "laboratory",
    description: "Глюкоза, АЛТ, АСТ, билирубин, креатинин, мочевина, общий белок.",
    unit: "комплекс",
  },
  {
    nameRu: "Липидный профиль",
    nameKk: "Липидті профиль",
    nameEn: "Lipid Profile",
    synonyms: ["липидограмма", "холестерин", "lipid panel", "cholesterol test", "ЛПНП", "ЛПВП"],
    category: "laboratory",
    description: "Холестерин общий, ЛПНП, ЛПВП, триглицериды.",
    unit: "комплекс",
  },
  {
    nameRu: "Глюкоза крови",
    nameKk: "Қан глюкозасы",
    nameEn: "Blood Glucose",
    synonyms: ["сахар крови", "glucose", "fasting glucose", "глюкоза натощак"],
    category: "laboratory",
    description: "Определение уровня глюкозы натощак.",
    unit: "шт",
  },
  {
    nameRu: "Гликированный гемоглобин (HbA1c)",
    nameKk: "Гликоланған гемоглобин",
    nameEn: "Glycated Hemoglobin (HbA1c)",
    synonyms: ["HbA1c", "гемоглобин гликированный", "A1C", "гликированный"],
    category: "laboratory",
    description: "Средний уровень сахара за 3 месяца.",
    unit: "шт",
  },
  {
    nameRu: "Тиреотропный гормон (ТТГ)",
    nameKk: "Тиреотропты гормон",
    nameEn: "Thyroid Stimulating Hormone (TSH)",
    synonyms: ["ТТГ", "TSH", "тиреотропин", "thyroid stimulating hormone"],
    category: "laboratory",
    description: "Оценка функции щитовидной железы.",
    unit: "шт",
  },
  {
    nameRu: "Свободный Т4",
    nameKk: "Еркін Т4",
    nameEn: "Free T4",
    synonyms: ["Т4 свободный", "free thyroxine", "FT4", "тироксин"],
    category: "laboratory",
    description: "Свободный тироксин.",
    unit: "шт",
  },
  {
    nameRu: "Витамин D (25-OH)",
    nameKk: "D дәрумені (25-OH)",
    nameEn: "Vitamin D (25-OH)",
    synonyms: ["25-OH витамин D", "кальцидиол", "витамин Д", "vitamin D3", "cholecalciferol test"],
    category: "laboratory",
    description: "Определение уровня 25-гидроксивитамина D.",
    unit: "шт",
  },
  {
    nameRu: "Витамин B12",
    nameKk: "B12 дәрумені",
    nameEn: "Vitamin B12",
    synonyms: ["цианокобаламин", "cobalamin", "B12", "кобаламин"],
    category: "laboratory",
    description: "Уровень витамина B12 в сыворотке.",
    unit: "шт",
  },
  {
    nameRu: "Ферритин",
    nameKk: "Ферритин",
    nameEn: "Ferritin",
    synonyms: ["ферритин сыворотки", "serum ferritin", "запас железа"],
    category: "laboratory",
    description: "Показатель запасов железа в организме.",
    unit: "шт",
  },
  {
    nameRu: "С-реактивный белок",
    nameKk: "С-реактивті ақуыз",
    nameEn: "C-Reactive Protein (CRP)",
    synonyms: ["СРБ", "CRP", "c-reactive protein", "реактивный белок"],
    category: "laboratory",
    description: "Маркер острого воспаления.",
    unit: "шт",
  },
  {
    nameRu: "ПСА общий",
    nameKk: "Жалпы ПСА",
    nameEn: "Prostate-Specific Antigen (PSA)",
    synonyms: ["ПСА", "PSA", "простат-специфический антиген", "prostate antigen"],
    category: "laboratory",
    description: "Маркер заболеваний предстательной железы.",
    unit: "шт",
  },
  {
    nameRu: "Коагулограмма",
    nameKk: "Коагулограмма",
    nameEn: "Coagulogram",
    synonyms: ["свертываемость крови", "coagulation panel", "МНО", "INR", "фибриноген"],
    category: "laboratory",
    description: "Оценка свёртывающей системы крови.",
    unit: "комплекс",
  },
  {
    nameRu: "Группа крови и резус-фактор",
    nameKk: "Қан тобы мен резус-фактор",
    nameEn: "Blood Type & Rh Factor",
    synonyms: ["группа крови", "резус", "blood group", "Rh", "ABO"],
    category: "laboratory",
    description: "Определение группы крови и резус-принадлежности.",
    unit: "шт",
  },
  {
    nameRu: "Инсулин",
    nameKk: "Инсулин",
    nameEn: "Insulin",
    synonyms: ["инсулин сыворотки", "serum insulin", "insulin level"],
    category: "laboratory",
    description: "Уровень инсулина натощак.",
    unit: "шт",
  },
  {
    nameRu: "Пролактин",
    nameKk: "Пролактин",
    nameEn: "Prolactin",
    synonyms: ["пролактин сыворотки", "mammary hormone", "PRL"],
    category: "laboratory",
    description: "Гормон лактации.",
    unit: "шт",
  },
  {
    nameRu: "Эстрадиол",
    nameKk: "Эстрадиол",
    nameEn: "Estradiol",
    synonyms: ["E2", "эстрадиол сыворотки", "estradiol level"],
    category: "laboratory",
    description: "Женский половой гормон.",
    unit: "шт",
  },
  {
    nameRu: "Тестостерон общий",
    nameKk: "Жалпы тестостерон",
    nameEn: "Total Testosterone",
    synonyms: ["тестостерон", "total testosterone", "male hormone"],
    category: "laboratory",
    description: "Мужской половой гормон.",
    unit: "шт",
  },
  {
    nameRu: "ПЦР-тест на COVID-19",
    nameKk: "COVID-19 ПТР тесті",
    nameEn: "COVID-19 PCR Test",
    synonyms: ["ПЦР ковид", "COVID PCR", "SARS-CoV-2 PCR", "ковид тест", "коронавирус"],
    category: "laboratory",
    description: "Молекулярная диагностика SARS-CoV-2.",
    unit: "шт",
  },
  {
    nameRu: "Анализ кала на яйца гельминтов",
    nameKk: "Нәжісті гельминт жұмыртқаларына талдау",
    nameEn: "Stool Ova & Parasites",
    synonyms: ["яйца глист", "кал на яйца", "stool ova", "parasites stool", "ОиП"],
    category: "laboratory",
    description: "Диагностика гельминтозов.",
    unit: "шт",
  },
  {
    nameRu: "Посев мочи на флору",
    nameKk: "Зәрді флораға егу",
    nameEn: "Urine Culture",
    synonyms: ["бакпосев мочи", "urine culture", "посев мочи", "bacterial culture urine"],
    category: "laboratory",
    description: "Культуральное исследование мочи с определением чувствительности к антибиотикам.",
    unit: "шт",
  },
  // ---- Laboratory additions (28) ----
  {
    nameRu: "Аланинаминотрансфераза (АЛТ)",
    nameKk: "Аланинаминотрансфераза (АЛТ)",
    nameEn: "Alanine Aminotransferase (ALT)",
    synonyms: ["АЛТ", "ALT", "аланинаминотрансфераза", "SGPT", "АлАТ"],
    category: "laboratory",
    description: "Печёночный фермент, маркер повреждения гепатоцитов.",
    unit: "шт",
  },
  {
    nameRu: "Аспартатаминотрансфераза (АСТ)",
    nameKk: "Аспартатаминотрансфераза (АСТ)",
    nameEn: "Aspartate Aminotransferase (AST)",
    synonyms: ["АСТ", "AST", "аспартатаминотрансфераза", "SGOT", "АсАТ"],
    category: "laboratory",
    description: "Фермент печени и сердечной мышцы.",
    unit: "шт",
  },
  {
    nameRu: "Билирубин общий",
    nameKk: "Жалпы билирубин",
    nameEn: "Total Bilirubin",
    synonyms: ["билирубин", "total bilirubin", "TBIL", "билирубин сыворотки"],
    category: "laboratory",
    description: "Пигмент крови, маркер функции печени и желчевыводящих путей.",
    unit: "шт",
  },
  {
    nameRu: "Креатинин",
    nameKk: "Креатинин",
    nameEn: "Creatinine",
    synonyms: ["креатинин крови", "serum creatinine", "Cr", "креатинин сыворотки"],
    category: "laboratory",
    description: "Маркер функции почек.",
    unit: "шт",
  },
  {
    nameRu: "Мочевина крови",
    nameKk: "Қан несепзі",
    nameEn: "Blood Urea",
    synonyms: ["мочевина", "urea", "BUN", "азот мочевины"],
    category: "laboratory",
    description: "Показатель белкового обмена и функции почек.",
    unit: "шт",
  },
  {
    nameRu: "Общий белок",
    nameKk: "Жалпы ақуыз",
    nameEn: "Total Protein",
    synonyms: ["белок крови", "total protein", "TP", "общий белок сыворотки"],
    category: "laboratory",
    description: "Суммарное содержание белков в сыворотке крови.",
    unit: "шт",
  },
  {
    nameRu: "Железо сыворотки",
    nameKk: "Сарысудың темірі",
    nameEn: "Serum Iron",
    synonyms: ["железо крови", "serum iron", "Fe", "сывороточное железо"],
    category: "laboratory",
    description: "Уровень железа в сыворотке крови.",
    unit: "шт",
  },
  {
    nameRu: "Электролиты (калий, натрий, хлор)",
    nameKk: "Электролиттер (калий, натрий, хлор)",
    nameEn: "Electrolytes Panel (K, Na, Cl)",
    synonyms: ["электролиты", "electrolytes", "калий-натрий", "K Na Cl", "ионограмма"],
    category: "laboratory",
    description: "Определение уровня калия, натрия и хлора в крови.",
    unit: "комплекс",
  },
  {
    nameRu: "Кальций общий",
    nameKk: "Жалпы кальций",
    nameEn: "Total Calcium",
    synonyms: ["кальций крови", "total calcium", "Ca", "кальций сыворотки"],
    category: "laboratory",
    description: "Уровень общего кальция в сыворотке.",
    unit: "шт",
  },
  {
    nameRu: "Гамма-глутамилтрансфераза (ГГТ)",
    nameKk: "Гамма-глутамилтрансфераза (ГГТ)",
    nameEn: "Gamma-Glutamyl Transferase (GGT)",
    synonyms: ["ГГТ", "GGT", "гамма-ГТ", "gamma-GT", "γ-GT"],
    category: "laboratory",
    description: "Фермент, маркер заболеваний печени и желчных путей.",
    unit: "шт",
  },
  {
    nameRu: "Щелочная фосфатаза",
    nameKk: "Сілтілі фосфатаза",
    nameEn: "Alkaline Phosphatase (ALP)",
    synonyms: ["ЩФ", "ALP", "щелочная фосфатаза", "alk phos"],
    category: "laboratory",
    description: "Фермент печени и костной ткани.",
    unit: "шт",
  },
  {
    nameRu: "Мочевая кислота",
    nameKk: "Несеп қышқылы",
    nameEn: "Uric Acid",
    synonyms: ["ураты", "uric acid", "UA", "мочевая кислота крови"],
    category: "laboratory",
    description: "Маркер подагры и нарушения пуринового обмена.",
    unit: "шт",
  },
  {
    nameRu: "Лактатдегидрогеназа (ЛДГ)",
    nameKk: "Лактатдегидрогеназа (ЛДГ)",
    nameEn: "Lactate Dehydrogenase (LDH)",
    synonyms: ["ЛДГ", "LDH", "лактатдегидрогеназа", "lactate dehydrogenase"],
    category: "laboratory",
    description: "Фермент, маркер тканевого повреждения.",
    unit: "шт",
  },
  {
    nameRu: "Липаза",
    nameKk: "Липаза",
    nameEn: "Lipase",
    synonyms: ["липаза панкреатическая", "pancreatic lipase", "сывороточная липаза"],
    category: "laboratory",
    description: "Фермент поджелудочной железы.",
    unit: "шт",
  },
  {
    nameRu: "Ревматоидный фактор",
    nameKk: "Ревматоидты фактор",
    nameEn: "Rheumatoid Factor (RF)",
    synonyms: ["РФ", "RF", "ревмофактор", "rheumatoid factor"],
    category: "laboratory",
    description: "Аутоантитело, маркер ревматоидного артрита.",
    unit: "шт",
  },
  {
    nameRu: "Антинуклеарный фактор (АНФ)",
    nameKk: "Антиядролық фактор (АЯФ)",
    nameEn: "Antinuclear Antibody (ANA)",
    synonyms: ["АНФ", "ANA", "антинуклеарные антитела", "antinuclear factor"],
    category: "laboratory",
    description: "Маркер системных аутоиммунных заболеваний.",
    unit: "шт",
  },
  {
    nameRu: "Антитела к ТПО (АТ-ТПО)",
    nameKk: "ТПО-ға антиденелер (АТ-ТПО)",
    nameEn: "Anti-Thyroid Peroxidase (Anti-TPO)",
    synonyms: ["АТ-ТПО", "Anti-TPO", "антитела к тиреопероксидазе", "anti-TPO Ab"],
    category: "laboratory",
    description: "Аутоантитела к тиреоидной пероксидазе.",
    unit: "шт",
  },
  {
    nameRu: "Лютеинизирующий гормон (ЛГ)",
    nameKk: "Лютеиндеуші гормон (ЛГ)",
    nameEn: "Luteinizing Hormone (LH)",
    synonyms: ["ЛГ", "LH", "лютропин", "luteinizing hormone"],
    category: "laboratory",
    description: "Гонадотропный гормон гипофиза.",
    unit: "шт",
  },
  {
    nameRu: "Фолликулостимулирующий гормон (ФСГ)",
    nameKk: "Фолликулостимулдеуші гормон (ФСГ)",
    nameEn: "Follicle-Stimulating Hormone (FSH)",
    synonyms: ["ФСГ", "FSH", "фоллитропин", "follicle-stimulating hormone"],
    category: "laboratory",
    description: "Гонадотропный гормон гипофиза.",
    unit: "шт",
  },
  {
    nameRu: "Прогестерон",
    nameKk: "Прогестерон",
    nameEn: "Progesterone",
    synonyms: ["прогестерон сыворотки", "serum progesterone", "P4"],
    category: "laboratory",
    description: "Гормон жёлтого тела.",
    unit: "шт",
  },
  {
    nameRu: "Кортизол",
    nameKk: "Кортизол",
    nameEn: "Cortisol",
    synonyms: ["кортизол сыворотки", "serum cortisol", "гидрокортизон"],
    category: "laboratory",
    description: "Гормон коры надпочечников.",
    unit: "шт",
  },
  {
    nameRu: "Антимюллеров гормон (АМГ)",
    nameKk: "Антимюллери гормоны (АМГ)",
    nameEn: "Anti-Müllerian Hormone (AMH)",
    synonyms: ["АМГ", "AMH", "антимюллеров", "anti-mullerian hormone"],
    category: "laboratory",
    description: "Маркер овариального резерва.",
    unit: "шт",
  },
  {
    nameRu: "Хорионический гонадотропин (ХГЧ)",
    nameKk: "Хориондық гонадотропин (ХГЧ)",
    nameEn: "Human Chorionic Gonadotropin (hCG)",
    synonyms: ["ХГЧ", "hCG", "ХГ", "беременность гормон", "pregnancy test blood"],
    category: "laboratory",
    description: "Гормон беременности.",
    unit: "шт",
  },
  {
    nameRu: "Иммуноглобулин E (IgE)",
    nameKk: "Иммуноглобулин E (IgE)",
    nameEn: "Immunoglobulin E (IgE)",
    synonyms: ["IgE", "общий IgE", "total IgE", "иммуноглобулин Е"],
    category: "laboratory",
    description: "Маркер аллергических реакций.",
    unit: "шт",
  },
  {
    nameRu: "Гепатит B (HBsAg)",
    nameKk: "В гепатиті (HBsAg)",
    nameEn: "Hepatitis B Surface Antigen (HBsAg)",
    synonyms: ["HBsAg", "гепатит В", "hepatitis B", "австралийский антиген"],
    category: "laboratory",
    description: "Поверхностный антиген вируса гепатита B.",
    unit: "шт",
  },
  {
    nameRu: "Гепатит C (Anti-HCV)",
    nameKk: "С гепатиті (Anti-HCV)",
    nameEn: "Hepatitis C Antibodies (Anti-HCV)",
    synonyms: ["Anti-HCV", "гепатит С", "hepatitis C", "HCV антитела"],
    category: "laboratory",
    description: "Антитела к вирусу гепатита C.",
    unit: "шт",
  },
  {
    nameRu: "ВИЧ (антитела)",
    nameKk: "ЖИТС (антиденелер)",
    nameEn: "HIV Antibodies",
    synonyms: ["ВИЧ", "HIV", "anti-HIV", "СПИД тест", "ВИЧ антитела"],
    category: "laboratory",
    description: "Скрининг антител к ВИЧ 1/2.",
    unit: "шт",
  },
  {
    nameRu: "Сифилис (RPR)",
    nameKk: "Мерез (RPR)",
    nameEn: "Syphilis Test (RPR)",
    synonyms: ["RPR", "РПГА", "сифилис", "syphilis", "реакция Вассермана", "RW"],
    category: "laboratory",
    description: "Скрининг сифилиса.",
    unit: "шт",
  },
  // ---- Doctor appointments (30) ----
  {
    nameRu: "Приём терапевта первичный",
    nameKk: "Терапевт қабылдауы (алғашқы)",
    nameEn: "General Practitioner Consultation (initial)",
    synonyms: ["приём терапевта", "терапевт", "GP visit", "врач-терапевт", "general practitioner"],
    category: "doctor_appointment",
    description: "Первичная консультация врача-терапевта.",
    unit: "приём",
  },
  {
    nameRu: "Приём кардиолога",
    nameKk: "Кардиолог қабылдауы",
    nameEn: "Cardiologist Consultation",
    synonyms: ["кардиолог", "cardiologist", "врач-кардиолог", "сердце врач"],
    category: "doctor_appointment",
    description: "Консультация врача-кардиолога.",
    unit: "приём",
  },
  {
    nameRu: "Приём невролога",
    nameKk: "Невролог қабылдауы",
    nameEn: "Neurologist Consultation",
    synonyms: ["невролог", "neurologist", "нерв врач", "врач-невролог"],
    category: "doctor_appointment",
    description: "Консультация врача-невролога.",
    unit: "приём",
  },
  {
    nameRu: "Приём гинеколога",
    nameKk: "Гинеколог қабылдауы",
    nameEn: "Gynecologist Consultation",
    synonyms: ["гинеколог", "gynecologist", "женский врач", "врач-гинеколог"],
    category: "doctor_appointment",
    description: "Консультация врача-гинеколога.",
    unit: "приём",
  },
  {
    nameRu: "Приём уролога",
    nameKk: "Уролог қабылдауы",
    nameEn: "Urologist Consultation",
    synonyms: ["уролог", "urologist", "мужской врач", "врач-уролог"],
    category: "doctor_appointment",
    description: "Консультация врача-уролога.",
    unit: "приём",
  },
  {
    nameRu: "Приём эндокринолога",
    nameKk: "Эндокринолог қабылдауы",
    nameEn: "Endocrinologist Consultation",
    synonyms: ["эндокринолог", "endocrinologist", "гормоны врач", "врач-эндокринолог"],
    category: "doctor_appointment",
    description: "Консультация врача-эндокринолога.",
    unit: "приём",
  },
  {
    nameRu: "Приём оториноларинголога (ЛОР)",
    nameKk: "ЛОР қабылдауы",
    nameEn: "ENT Consultation",
    synonyms: ["ЛОР", "оториноларинголог", "ENT", "ухо горло нос", "отоларинголог"],
    category: "doctor_appointment",
    description: "Консультация ЛОР-врача.",
    unit: "приём",
  },
  {
    nameRu: "Приём офтальмолога",
    nameKk: "Офтальмолог қабылдауы",
    nameEn: "Ophthalmologist Consultation",
    synonyms: ["офтальмолог", "ophthalmologist", "окулист", "глазной врач"],
    category: "doctor_appointment",
    description: "Консультация врача-офтальмолога.",
    unit: "приём",
  },
  {
    nameRu: "Приём дерматолога",
    nameKk: "Дерматолог қабылдауы",
    nameEn: "Dermatologist Consultation",
    synonyms: ["дерматолог", "dermatologist", "кожный врач", "врач-дерматолог"],
    category: "doctor_appointment",
    description: "Консультация врача-дерматолога.",
    unit: "приём",
  },
  {
    nameRu: "Приём педиатра",
    nameKk: "Педиатр қабылдауы",
    nameEn: "Pediatrician Consultation",
    synonyms: ["педиатр", "pediatrician", "детский врач", "врач-педиатр"],
    category: "doctor_appointment",
    description: "Консультация врача-педиатра.",
    unit: "приём",
  },
  {
    nameRu: "Приём гастроэнтеролога",
    nameKk: "Гастроэнтеролог қабылдауы",
    nameEn: "Gastroenterologist Consultation",
    synonyms: ["гастроэнтеролог", "gastroenterologist", "желудок врач", "врач-гастроэнтеролог"],
    category: "doctor_appointment",
    description: "Консультация врача-гастроэнтеролога.",
    unit: "приём",
  },
  {
    nameRu: "Приём хирурга",
    nameKk: "Хирург қабылдауы",
    nameEn: "Surgeon Consultation",
    synonyms: ["хирург", "surgeon", "врач-хирург"],
    category: "doctor_appointment",
    description: "Консультация врача-хирурга.",
    unit: "приём",
  },
  // ---- Doctor appointments additions (18) ----
  {
    nameRu: "Приём аллерголога-иммунолога",
    nameKk: "Аллерголог-иммунолог қабылдауы",
    nameEn: "Allergist-Immunologist Consultation",
    synonyms: ["аллерголог", "allergist", "иммунолог", "врач-аллерголог"],
    category: "doctor_appointment",
    description: "Консультация врача-аллерголога-иммунолога.",
    unit: "приём",
  },
  {
    nameRu: "Приём пульмонолога",
    nameKk: "Пульмонолог қабылдауы",
    nameEn: "Pulmonologist Consultation",
    synonyms: ["пульмонолог", "pulmonologist", "врач-пульмонолог", "лёгкие врач"],
    category: "doctor_appointment",
    description: "Консультация врача-пульмонолога.",
    unit: "приём",
  },
  {
    nameRu: "Приём ревматолога",
    nameKk: "Ревматолог қабылдауы",
    nameEn: "Rheumatologist Consultation",
    synonyms: ["ревматолог", "rheumatologist", "врач-ревматолог", "суставы врач"],
    category: "doctor_appointment",
    description: "Консультация врача-ревматолога.",
    unit: "приём",
  },
  {
    nameRu: "Приём гематолога",
    nameKk: "Гематолог қабылдауы",
    nameEn: "Hematologist Consultation",
    synonyms: ["гематолог", "hematologist", "врач-гематолог", "кровь врач"],
    category: "doctor_appointment",
    description: "Консультация врача-гематолога.",
    unit: "приём",
  },
  {
    nameRu: "Приём психиатра",
    nameKk: "Психиатр қабылдауы",
    nameEn: "Psychiatrist Consultation",
    synonyms: ["психиатр", "psychiatrist", "врач-психиатр"],
    category: "doctor_appointment",
    description: "Консультация врача-психиатра.",
    unit: "приём",
  },
  {
    nameRu: "Приём психотерапевта",
    nameKk: "Психотерапевт қабылдауы",
    nameEn: "Psychotherapist Consultation",
    synonyms: ["психотерапевт", "psychotherapist", "врач-психотерапевт"],
    category: "doctor_appointment",
    description: "Консультация врача-психотерапевта.",
    unit: "приём",
  },
  {
    nameRu: "Приём нарколога",
    nameKk: "Нарколог қабылдауы",
    nameEn: "Narcologist Consultation",
    synonyms: ["нарколог", "narcologist", "врач-нарколог", "наркологический"],
    category: "doctor_appointment",
    description: "Консультация врача-нарколога.",
    unit: "приём",
  },
  {
    nameRu: "Приём инфекциониста",
    nameKk: "Инфекционист қабылдауы",
    nameEn: "Infectious Disease Specialist Consultation",
    synonyms: ["инфекционист", "infectious disease", "врач-инфекционист", "инфекции врач"],
    category: "doctor_appointment",
    description: "Консультация врача-инфекциониста.",
    unit: "приём",
  },
  {
    nameRu: "Приём фтизиатра",
    nameKk: "Фтизиатр қабылдауы",
    nameEn: "Phthisiatrician Consultation",
    synonyms: ["фтизиатр", "phthisiatrician", "туберкулёз врач", "врач-фтизиатр"],
    category: "doctor_appointment",
    description: "Консультация врача-фтизиатра (специалиста по туберкулёзу).",
    unit: "приём",
  },
  {
    nameRu: "Приём маммолога",
    nameKk: "Маммолог қабылдауы",
    nameEn: "Mammologist Consultation",
    synonyms: ["маммолог", "mammologist", "врач-маммолог", "молочная железа врач"],
    category: "doctor_appointment",
    description: "Консультация врача-маммолога.",
    unit: "приём",
  },
  {
    nameRu: "Приём онколога",
    nameKk: "Онколог қабылдауы",
    nameEn: "Oncologist Consultation",
    synonyms: ["онколог", "oncologist", "врач-онколог", "рак врач"],
    category: "doctor_appointment",
    description: "Консультация врача-онколога.",
    unit: "приём",
  },
  {
    nameRu: "Приём нефролога",
    nameKk: "Нефролог қабылдауы",
    nameEn: "Nephrologist Consultation",
    synonyms: ["нефролог", "nephrologist", "врач-нефролог", "почки врач"],
    category: "doctor_appointment",
    description: "Консультация врача-нефролога.",
    unit: "приём",
  },
  {
    nameRu: "Приём проктолога",
    nameKk: "Проктолог қабылдауы",
    nameEn: "Proctologist Consultation",
    synonyms: ["проктолог", "proctologist", "врач-проктолог", "колопроктолог"],
    category: "doctor_appointment",
    description: "Консультация врача-проктолога.",
    unit: "приём",
  },
  {
    nameRu: "Приём флеболога",
    nameKk: "Флеболог қабылдауы",
    nameEn: "Phlebologist Consultation",
    synonyms: ["флеболог", "phlebologist", "врач-флеболог", "вены врач"],
    category: "doctor_appointment",
    description: "Консультация врача-флеболога.",
    unit: "приём",
  },
  {
    nameRu: "Приём мануального терапевта",
    nameKk: "Мануальды терапевт қабылдауы",
    nameEn: "Manual Therapist Consultation",
    synonyms: ["мануальный терапевт", "manual therapist", "остеопат", "chiropractor"],
    category: "doctor_appointment",
    description: "Консультация врача мануальной терапии.",
    unit: "приём",
  },
  {
    nameRu: "Приём стоматолога-терапевта",
    nameKk: "Стоматолог-терапевт қабылдауы",
    nameEn: "Dentist (Therapeutic) Consultation",
    synonyms: ["стоматолог", "dentist", "зубной врач", "стоматолог-терапевт"],
    category: "doctor_appointment",
    description: "Консультация врача-стоматолога-терапевта.",
    unit: "приём",
  },
  {
    nameRu: "Приём ортопеда-травматолога",
    nameKk: "Ортопед-травматолог қабылдауы",
    nameEn: "Orthopedic Traumatologist Consultation",
    synonyms: ["ортопед", "травматолог", "orthopedist", "traumatologist", "врач-ортопед"],
    category: "doctor_appointment",
    description: "Консультация врача-ортопеда-травматолога.",
    unit: "приём",
  },
  {
    nameRu: "Приём челюстно-лицевого хирурга",
    nameKk: "Жақ-бет хирургі қабылдауы",
    nameEn: "Maxillofacial Surgeon Consultation",
    synonyms: ["челюстно-лицевой хирург", "maxillofacial surgeon", "ЧЛХ", "врач-челюстно-лицевой хирург"],
    category: "doctor_appointment",
    description: "Консультация врача челюстно-лицевого хирурга.",
    unit: "приём",
  },
  // ---- Diagnostics (25) ----
  {
    nameRu: "УЗИ органов брюшной полости",
    nameKk: "Ішкі ағзалардың УДТ",
    nameEn: "Abdominal Ultrasound",
    synonyms: ["УЗИ брюшной полости", "abdominal ultrasound", "УЗИ ОБП", "сонография живота"],
    category: "diagnostics",
    description: "Ультразвуковое исследование органов брюшной полости.",
    unit: "исследование",
  },
  {
    nameRu: "УЗИ щитовидной железы",
    nameKk: "Қалқанша безінің УДТ",
    nameEn: "Thyroid Ultrasound",
    synonyms: ["УЗИ щитовидки", "thyroid ultrasound", "УЗИ ЩЖ"],
    category: "diagnostics",
    description: "Ультразвуковое исследование щитовидной железы.",
    unit: "исследование",
  },
  {
    nameRu: "УЗИ органов малого таза",
    nameKk: "Кіші жамбас ағзаларының УДТ",
    nameEn: "Pelvic Ultrasound",
    synonyms: ["УЗИ малого таза", "pelvic ultrasound", "УЗИ ОМТ", "гинекологическое УЗИ"],
    category: "diagnostics",
    description: "Ультразвуковое исследование органов малого таза.",
    unit: "исследование",
  },
  {
    nameRu: "ЭКГ (электрокардиограмма)",
    nameKk: "ЭКГ (электрокардиограмма)",
    nameEn: "Electrocardiogram (ECG)",
    synonyms: ["ЭКГ", "ECG", "электрокардиография", "кардиограмма", "EKG"],
    category: "diagnostics",
    description: "Регистрация электрической активности сердца.",
    unit: "исследование",
  },
  {
    nameRu: "ЭхоКГ (УЗИ сердца)",
    nameKk: "ЭхоКГ (жүрек УДТ)",
    nameEn: "Echocardiography",
    synonyms: ["ЭхоКГ", "УЗИ сердца", "echocardiogram", "echo heart", "эхокардиография"],
    category: "diagnostics",
    description: "Ультразвуковое исследование сердца.",
    unit: "исследование",
  },
  {
    nameRu: "Рентген грудной клетки",
    nameKk: "Кеуде қуысының рентгені",
    nameEn: "Chest X-Ray",
    synonyms: ["рентген лёгких", "chest X-ray", "флюорография", "CXR", "chest radiograph"],
    category: "diagnostics",
    description: "Рентгенологическое исследование органов грудной клетки.",
    unit: "исследование",
  },
  {
    nameRu: "МРТ головного мозга",
    nameKk: "Ми МРТ",
    nameEn: "Brain MRI",
    synonyms: ["МРТ головы", "brain MRI", "МРТ головного мозга", "magnetic resonance brain"],
    category: "diagnostics",
    description: "Магнитно-резонансная томография головного мозга.",
    unit: "исследование",
  },
  {
    nameRu: "КТ грудной клетки",
    nameKk: "Кеуде қуысының КТ",
    nameEn: "Chest CT Scan",
    synonyms: ["КТ лёгких", "chest CT", "компьютерная томография грудной клетки", "CT chest"],
    category: "diagnostics",
    description: "Компьютерная томография органов грудной клетки.",
    unit: "исследование",
  },
  {
    nameRu: "Маммография",
    nameKk: "Маммография",
    nameEn: "Mammography",
    synonyms: ["маммограмма", "mammogram", "рентген молочной железы", "breast X-ray"],
    category: "diagnostics",
    description: "Рентгенологическое исследование молочных желёз.",
    unit: "исследование",
  },
  {
    nameRu: "Холтеровское мониторирование ЭКГ",
    nameKk: "Холтер мониторингі",
    nameEn: "Holter ECG Monitoring",
    synonyms: ["Холтер", "Holter monitor", "суточное мониторирование ЭКГ", "24h ECG"],
    category: "diagnostics",
    description: "Суточная регистрация ЭКГ.",
    unit: "исследование",
  },
  {
    nameRu: "СМАД (суточное мониторирование давления)",
    nameKk: "СМАД",
    nameEn: "24h Blood Pressure Monitoring (ABPM)",
    synonyms: ["СМАД", "ABPM", "суточное давление", "blood pressure monitoring"],
    category: "diagnostics",
    description: "Суточное мониторирование артериального давления.",
    unit: "исследование",
  },
  {
    nameRu: "Гастроскопия (ФГДС)",
    nameKk: "Гастроскопия (ФГДС)",
    nameEn: "Gastroscopy (EGD)",
    synonyms: ["ФГДС", "gastroscopy", "ЭГДС", "EGD", "гастроскопия", "желудок зонд"],
    category: "diagnostics",
    description: "Эндоскопическое исследование пищевода, желудка и двенадцатиперстной кишки.",
    unit: "исследование",
  },
  // ---- Diagnostics additions (13) ----
  {
    nameRu: "УЗИ почек и надпочечников",
    nameKk: "Бүйрек пен бүйрек үсті бездерінің УДТ",
    nameEn: "Kidney & Adrenal Ultrasound",
    synonyms: ["УЗИ почек", "kidney ultrasound", "УЗИ надпочечников", "renal ultrasound"],
    category: "diagnostics",
    description: "Ультразвуковое исследование почек и надпочечников.",
    unit: "исследование",
  },
  {
    nameRu: "УЗИ молочных желёз",
    nameKk: "Сүт бездерінің УДТ",
    nameEn: "Breast Ultrasound",
    synonyms: ["УЗИ молочных", "breast ultrasound", "УЗИ груди", "sonomammography"],
    category: "diagnostics",
    description: "Ультразвуковое исследование молочных желёз.",
    unit: "исследование",
  },
  {
    nameRu: "ТРУЗИ предстательной железы",
    nameKk: "Қуық асты безінің ТРУДТ",
    nameEn: "Transrectal Prostate Ultrasound (TRUS)",
    synonyms: ["ТРУЗИ", "TRUS", "УЗИ простаты", "prostate ultrasound transrectal"],
    category: "diagnostics",
    description: "Трансректальное ультразвуковое исследование предстательной железы.",
    unit: "исследование",
  },
  {
    nameRu: "УЗДГ сосудов нижних конечностей",
    nameKk: "Аяқ тамырларының УДТ (доплер)",
    nameEn: "Lower Limb Vascular Doppler Ultrasound",
    synonyms: ["УЗДГ", "доплер сосудов", "vascular doppler", "УЗИ вен нижних конечностей", "доплерография"],
    category: "diagnostics",
    description: "Ультразвуковое допплерографическое исследование сосудов нижних конечностей.",
    unit: "исследование",
  },
  {
    nameRu: "МРТ пояснично-крестцового отдела позвоночника",
    nameKk: "Бел-құйымшақ омыртқа бөлімінің МРТ",
    nameEn: "Lumbar Spine MRI",
    synonyms: ["МРТ поясничного отдела", "lumbar MRI", "МРТ позвоночника", "МРТ крестца"],
    category: "diagnostics",
    description: "Магнитно-резонансная томография пояснично-крестцового отдела позвоночника.",
    unit: "исследование",
  },
  {
    nameRu: "МРТ коленного сустава",
    nameKk: "Тізе буынының МРТ",
    nameEn: "Knee Joint MRI",
    synonyms: ["МРТ колена", "knee MRI", "МРТ коленного сустава", "knee joint MRI"],
    category: "diagnostics",
    description: "Магнитно-резонансная томография коленного сустава.",
    unit: "исследование",
  },
  {
    nameRu: "КТ головного мозга",
    nameKk: "Мидың КТ",
    nameEn: "Brain CT Scan",
    synonyms: ["КТ головы", "brain CT", "компьютерная томография головного мозга", "CT head"],
    category: "diagnostics",
    description: "Компьютерная томография головного мозга.",
    unit: "исследование",
  },
  {
    nameRu: "ЭЭГ (электроэнцефалограмма)",
    nameKk: "ЭЭГ (электроэнцефалограмма)",
    nameEn: "Electroencephalogram (EEG)",
    synonyms: ["ЭЭГ", "EEG", "электроэнцефалография", "brain wave test"],
    category: "diagnostics",
    description: "Регистрация электрической активности головного мозга.",
    unit: "исследование",
  },
  {
    nameRu: "Спирометрия",
    nameKk: "Спирометрия",
    nameEn: "Spirometry",
    synonyms: ["функция внешнего дыхания", "ФВД", "spirometry", "lung function test"],
    category: "diagnostics",
    description: "Исследование функции внешнего дыхания.",
    unit: "исследование",
  },
  {
    nameRu: "Денситометрия",
    nameKk: "Денситометрия",
    nameEn: "Bone Densitometry (DEXA)",
    synonyms: ["денситометрия костей", "DEXA", "bone density", "плотность костей"],
    category: "diagnostics",
    description: "Определение минеральной плотности костной ткани.",
    unit: "исследование",
  },
  {
    nameRu: "Колоноскопия (ФКС)",
    nameKk: "Колоноскопия (ФКС)",
    nameEn: "Colonoscopy",
    synonyms: ["ФКС", "colonoscopy", "колоноскоп", "fibercolonscopy", "фиброколоноскопия"],
    category: "diagnostics",
    description: "Эндоскопическое исследование толстого кишечника.",
    unit: "исследование",
  },
  {
    nameRu: "Бронхоскопия",
    nameKk: "Бронхоскопия",
    nameEn: "Bronchoscopy",
    synonyms: ["бронхоскоп", "bronchoscopy", "эндоскопия бронхов"],
    category: "diagnostics",
    description: "Эндоскопическое исследование бронхов.",
    unit: "исследование",
  },
  {
    nameRu: "Флюорография цифровая",
    nameKk: "Цифрлық флюорография",
    nameEn: "Digital Fluorography",
    synonyms: ["флюорография", "fluorography", "флюшка", "скрининг лёгких"],
    category: "diagnostics",
    description: "Цифровое рентгенологическое скрининговое исследование органов грудной клетки.",
    unit: "исследование",
  },
  // ---- Procedures (15) ----
  {
    nameRu: "Внутривенные инъекции",
    nameKk: "Көктамыр ішілік инъекциялар",
    nameEn: "Intravenous Injection",
    synonyms: ["внутривенный укол", "IV injection", "капельница", "IV drip", "инфузия"],
    category: "procedure",
    description: "Введение препарата внутривенно.",
    unit: "процедура",
  },
  {
    nameRu: "Внутримышечные инъекции",
    nameKk: "Бұлшықет ішілік инъекциялар",
    nameEn: "Intramuscular Injection",
    synonyms: ["внутримышечный укол", "IM injection", "укол в мышцу"],
    category: "procedure",
    description: "Введение препарата внутримышечно.",
    unit: "процедура",
  },
  {
    nameRu: "Физиотерапия",
    nameKk: "Физиотерапия",
    nameEn: "Physiotherapy",
    synonyms: ["физио", "physio", "физиотерапевтическая процедура", "physical therapy"],
    category: "procedure",
    description: "Лечебное применение физических факторов.",
    unit: "процедура",
  },
  {
    nameRu: "Массаж лечебный",
    nameKk: "Емдік массаж",
    nameEn: "Therapeutic Massage",
    synonyms: ["массаж", "massage", "medical massage", "лечебный массаж"],
    category: "procedure",
    description: "Лечебный массаж одной зоны.",
    unit: "процедура",
  },
  {
    nameRu: "Вакцинация от гриппа",
    nameKk: "Тұмауға қарсы вакцинация",
    nameEn: "Flu Vaccination",
    synonyms: ["прививка от гриппа", "flu shot", "вакцина грипп", "influenza vaccine"],
    category: "procedure",
    description: "Вакцинация против гриппа.",
    unit: "процедура",
  },
  {
    nameRu: "Электрофорез",
    nameKk: "Электрофорез",
    nameEn: "Electrophoresis",
    synonyms: ["электрофорез лекарственный", "iontophoresis", "гальванизация"],
    category: "procedure",
    description: "Введение лекарственных веществ через кожу постоянным током.",
    unit: "процедура",
  },
  // ---- Procedure additions (9) ----
  {
    nameRu: "Вакцинация АКДС",
    nameKk: "АКДС вакцинациясы",
    nameEn: "DTaP Vaccination",
    synonyms: ["АКДС", "DTaP", "прививка АКДС", "коклюш дифтерия столбняк"],
    category: "procedure",
    description: "Вакцинация против коклюша, дифтерии и столбняка.",
    unit: "процедура",
  },
  {
    nameRu: "Вакцинация против гепатита B",
    nameKk: "В гепатитіне қарсы вакцинация",
    nameEn: "Hepatitis B Vaccination",
    synonyms: ["прививка от гепатита B", "hepatitis B vaccine", "вакцина гепатит В", "HBV vaccine"],
    category: "procedure",
    description: "Вакцинация против вируса гепатита B.",
    unit: "процедура",
  },
  {
    nameRu: "Вакцинация против кори, краснухи, паротита (MMR)",
    nameKk: "Қызылша, қызамық, паротитке қарсы вакцинация",
    nameEn: "MMR Vaccination",
    synonyms: ["MMR", "вакцина MMR", "прививка корь краснуха паротит", "ККП"],
    category: "procedure",
    description: "Вакцинация против кори, краснухи и эпидемического паротита.",
    unit: "процедура",
  },
  {
    nameRu: "Вакцинация против клещевого энцефалита",
    nameKk: "Кене энцефалитіне қарсы вакцинация",
    nameEn: "Tick-borne Encephalitis Vaccination",
    synonyms: ["прививка от клещевого энцефалита", "tick encephalitis vaccine", "вакцина энцефалит", "TBE vaccine"],
    category: "procedure",
    description: "Вакцинация против клещевого энцефалита.",
    unit: "процедура",
  },
  {
    nameRu: "Вакцинация против ВПЧ",
    nameKk: "ВПЧ-ға қарсы вакцинация",
    nameEn: "HPV Vaccination",
    synonyms: ["прививка от ВПЧ", "HPV vaccine", "Гардасил", "Gardasil", "папиллома вирус вакцина"],
    category: "procedure",
    description: "Вакцинация против вируса папилломы человека.",
    unit: "процедура",
  },
  {
    nameRu: "Перевязка",
    nameKk: "Таңу",
    nameEn: "Wound Dressing",
    synonyms: ["перевязка раны", "dressing change", "bandage change", "обработка раны"],
    category: "procedure",
    description: "Перевязка раны с обработкой.",
    unit: "процедура",
  },
  {
    nameRu: "Снятие швов",
    nameKk: "Тігісті алу",
    nameEn: "Suture Removal",
    synonyms: ["снятие хирургических швов", "suture removal", "удаление швов", "stitches removal"],
    category: "procedure",
    description: "Снятие хирургических швов.",
    unit: "процедура",
  },
  {
    nameRu: "Вскрытие гнойника",
    nameKk: "Іріңдікті ашу",
    nameEn: "Abscess Incision & Drainage",
    synonyms: ["вскрытие абсцесса", "abscess drainage", "I&D", "вскрытие фурункула"],
    category: "procedure",
    description: "Хирургическое вскрытие и дренирование гнойника.",
    unit: "процедура",
  },
  {
    nameRu: "Пункция сустава",
    nameKk: "Буын пункциясы",
    nameEn: "Joint Puncture",
    synonyms: ["пункция коленного сустава", "joint aspiration", "артроцентез", "пункция сустава"],
    category: "procedure",
    description: "Пункция сустава с эвакуацией жидкости или введением препарата.",
    unit: "процедура",
  },
];

/** Major Kazakhstan cities with approximate map centers and known clinic clusters. */
export const KZ_CITIES = [
  { city: "Алматы", cityEn: "Almaty", lat: 43.222, lng: 76.8512 },
  { city: "Астана", cityEn: "Astana", lat: 51.1605, lng: 71.4704 },
  { city: "Шымкент", cityEn: "Shymkent", lat: 42.3417, lng: 69.59 },
  { city: "Актобе", cityEn: "Aktobe", lat: 50.2839, lng: 57.167 },
  { city: "Павлодар", cityEn: "Pavlodar", lat: 52.2873, lng: 76.9676 },
  { city: "Караганда", cityEn: "Karaganda", lat: 49.8047, lng: 73.1094 },
  { city: "Семей", cityEn: "Semey", lat: 50.4116, lng: 80.2236 },
  { city: "Атырау", cityEn: "Atyrau", lat: 47.1164, lng: 51.8823 },
] as const;

export type ClinicSourceDef = {
  sourceName: string;
  clinicName: string;
  city: string;
  address: string;
  phone: string;
  workingHours: string;
  sourceUrl: string;
  website: string;
  rating: number;
  onlineBooking: boolean;
  lat: number;
  lng: number;
};

/** 24 clinic source definitions across KZ cities (KDL, Invitro, Olymp, Helix, OnClinic, SultanZharbulov, GreenClinic, Medilux, Medicus, Сфера Здоровья, Дала Мед, Бэйбилайф, MEDISON, Эссен, Рахат Мед, etc.). */
export const CLINIC_SOURCES: ClinicSourceDef[] = [
  {
    sourceName: "KDL",
    clinicName: "Лаборатория KDL",
    city: "Алматы",
    address: "ул. Абылай хана, 38",
    phone: "+7 (727) 300-20-30",
    workingHours: "Пн–Сб 07:30–19:00, Вс 08:00–15:00",
    sourceUrl: "https://kdl.kz/almaty",
    website: "https://kdl.kz",
    rating: 4.6,
    onlineBooking: true,
    lat: 43.2389,
    lng: 76.8897,
  },
  {
    sourceName: "KDL",
    clinicName: "Лаборатория KDL",
    city: "Астана",
    address: "пр. Республики, 25",
    phone: "+7 (7172) 70-20-30",
    workingHours: "Пн–Сб 07:30–19:00, Вс 08:00–15:00",
    sourceUrl: "https://kdl.kz/astana",
    website: "https://kdl.kz",
    rating: 4.5,
    onlineBooking: true,
    lat: 51.1694,
    lng: 71.4491,
  },
  {
    sourceName: "Invitro",
    clinicName: "Лаборатория Инвитро",
    city: "Алматы",
    address: "пр. Достык, 132",
    phone: "+7 (727) 388-00-00",
    workingHours: "Ежедневно 07:00–20:00",
    sourceUrl: "https://invitro.kz/almaty",
    website: "https://invitro.kz",
    rating: 4.7,
    onlineBooking: true,
    lat: 43.2275,
    lng: 76.9519,
  },
  {
    sourceName: "Invitro",
    clinicName: "Лаборатория Инвитро",
    city: "Шымкент",
    address: "ул. Толе би, 12",
    phone: "+7 (7252) 50-00-00",
    workingHours: "Ежедневно 07:00–20:00",
    sourceUrl: "https://invitro.kz/shymkent",
    website: "https://invitro.kz",
    rating: 4.5,
    onlineBooking: true,
    lat: 42.3433,
    lng: 69.5893,
  },
  {
    sourceName: "Olymp",
    clinicName: "Медцентр Олимп",
    city: "Алматы",
    address: "ул. Тимирязева, 42",
    phone: "+7 (727) 355-50-50",
    workingHours: "Пн–Пт 08:00–20:00, Сб 09:00–17:00",
    sourceUrl: "https://olymp.kz/almaty",
    website: "https://olymp.kz",
    rating: 4.4,
    onlineBooking: true,
    lat: 43.2401,
    lng: 76.9289,
  },
  {
    sourceName: "Olymp",
    clinicName: "Медцентр Олимп",
    city: "Астана",
    address: "ул. Кенесары, 67",
    phone: "+7 (7172) 55-50-50",
    workingHours: "Пн–Пт 08:00–20:00, Сб 09:00–17:00",
    sourceUrl: "https://olymp.kz/astana",
    website: "https://olymp.kz",
    rating: 4.3,
    onlineBooking: true,
    lat: 51.1801,
    lng: 71.4189,
  },
  {
    sourceName: "Helix",
    clinicName: "Лаборатория Хеликс",
    city: "Караганда",
    address: "пр. Бухар жырау, 49",
    phone: "+7 (7212) 90-20-20",
    workingHours: "Пн–Сб 07:30–19:00",
    sourceUrl: "https://helix.kz/karaganda",
    website: "https://helix.kz",
    rating: 4.2,
    onlineBooking: false,
    lat: 49.8101,
    lng: 73.1151,
  },
  {
    sourceName: "Helix",
    clinicName: "Лаборатория Хеликс",
    city: "Павлодар",
    address: "ул. Ломова, 11",
    phone: "+7 (7182) 70-20-20",
    workingHours: "Пн–Сб 07:30–19:00",
    sourceUrl: "https://helix.kz/pavlodar",
    website: "https://helix.kz",
    rating: 4.1,
    onlineBooking: false,
    lat: 52.2921,
    lng: 76.9701,
  },
  {
    sourceName: "Medel",
    clinicName: "Клиника МЕДЭЛ",
    city: "Алматы",
    address: "ул. Макатаева, 117",
    phone: "+7 (727) 333-30-30",
    workingHours: "Круглосуточно",
    sourceUrl: "https://medel.kz",
    website: "https://medel.kz",
    rating: 4.5,
    onlineBooking: true,
    lat: 43.2612,
    lng: 76.8912,
  },
  {
    sourceName: "Medel",
    clinicName: "Клиника МЕДЭЛ",
    city: "Актобе",
    address: "пр. Абылхайыр хана, 42",
    phone: "+7 (7132) 90-30-30",
    workingHours: "Круглосуточно",
    sourceUrl: "https://medel.kz/aktobe",
    website: "https://medel.kz",
    rating: 4.4,
    onlineBooking: true,
    lat: 50.2901,
    lng: 57.1601,
  },
  {
    sourceName: "AksaiClinic",
    clinicName: "Аксайская клиника",
    city: "Атырау",
    address: "пр. Сатпаева, 14",
    phone: "+7 (7122) 35-15-15",
    workingHours: "Пн–Пт 08:00–18:00",
    sourceUrl: "https://aksai-clinic.kz",
    website: "https://aksai-clinic.kz",
    rating: 4.0,
    onlineBooking: false,
    lat: 47.1201,
    lng: 51.8801,
  },
  {
    sourceName: "MCK",
    clinicName: "Медицинский центр МЦК",
    city: "Семей",
    address: "ул. Абая, 156",
    phone: "+7 (7222) 52-22-22",
    workingHours: "Пн–Сб 08:00–19:00",
    sourceUrl: "https://mck.kz",
    website: "https://mck.kz",
    rating: 4.3,
    onlineBooking: true,
    lat: 50.4201,
    lng: 80.2201,
  },
  {
    sourceName: "OnClinic",
    clinicName: "Клиника Он Клиник",
    city: "Алматы",
    address: "пр. Абая, 88",
    phone: "+7 (727) 344-44-44",
    workingHours: "Пн–Сб 08:00–20:00, Вс 09:00–17:00",
    sourceUrl: "https://onclinic.kz/almaty",
    website: "https://onclinic.kz",
    rating: 4.4,
    onlineBooking: true,
    lat: 43.2567,
    lng: 76.9286,
  },
  {
    sourceName: "SultanZharbulov",
    clinicName: "Клиника Султана Жарбулова",
    city: "Астана",
    address: "ул. Бейбитшилик, 21",
    phone: "+7 (7172) 47-77-77",
    workingHours: "Пн–Пт 08:00–20:00, Сб 09:00–16:00",
    sourceUrl: "https://sultan-clinic.kz/astana",
    website: "https://sultan-clinic.kz",
    rating: 4.5,
    onlineBooking: true,
    lat: 51.1234,
    lng: 71.4309,
  },
  {
    sourceName: "GreenClinic",
    clinicName: "Грин Клиник",
    city: "Шымкент",
    address: "пр. Республики, 15",
    phone: "+7 (7252) 40-10-10",
    workingHours: "Пн–Сб 07:30–19:30, Вс 09:00–15:00",
    sourceUrl: "https://greenclinic.kz/shymkent",
    website: "https://greenclinic.kz",
    rating: 4.2,
    onlineBooking: false,
    lat: 42.3456,
    lng: 69.5945,
  },
  {
    sourceName: "Medilux",
    clinicName: "Медицинский центр Медилux",
    city: "Караганда",
    address: "ул. Ерубаева, 33",
    phone: "+7 (7212) 99-88-77",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://medilux.kz/karaganda",
    website: "https://medilux.kz",
    rating: 4.1,
    onlineBooking: true,
    lat: 49.8234,
    lng: 73.1656,
  },
  {
    sourceName: "Medicus",
    clinicName: "Медицинский центр Медикус",
    city: "Алматы",
    address: "ул. Тимирязева, 38",
    phone: "+7 (727) 311-22-33",
    workingHours: "Пн–Сб 08:00–20:00, Вс 09:00–15:00",
    sourceUrl: "https://medicus.kz/almaty",
    website: "https://medicus.kz",
    rating: 4.3,
    onlineBooking: true,
    lat: 43.2385,
    lng: 76.948,
  },
  {
    sourceName: "Medicus",
    clinicName: "Медицинский центр Медикус",
    city: "Астана",
    address: "ул. Бокейханова, 19",
    phone: "+7 (7172) 36-22-33",
    workingHours: "Пн–Сб 08:00–20:00, Вс 09:00–15:00",
    sourceUrl: "https://medicus.kz/astana",
    website: "https://medicus.kz",
    rating: 4.2,
    onlineBooking: true,
    lat: 51.1727,
    lng: 71.426,
  },
  {
    sourceName: "SferaZdorovya",
    clinicName: "Клиника Сфера Здоровья",
    city: "Шымкент",
    address: "ул. Желтоксан, 25",
    phone: "+7 (7252) 55-33-22",
    workingHours: "Пн–Пт 08:00–19:00, Сб 09:00–16:00",
    sourceUrl: "https://sfera-zdorovya.kz/shymkent",
    website: "https://sfera-zdorovya.kz",
    rating: 4.0,
    onlineBooking: false,
    lat: 42.342,
    lng: 69.59,
  },
  {
    sourceName: "DalaMed",
    clinicName: "Медицинский центр Дала Мед",
    city: "Актобе",
    address: "пр. Абилкайыр хана, 76",
    phone: "+7 (7132) 50-20-20",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://dala-med.kz/aktobe",
    website: "https://dala-med.kz",
    rating: 4.1,
    onlineBooking: true,
    lat: 50.295,
    lng: 57.165,
  },
  {
    sourceName: "Beibalaife",
    clinicName: "Перинатальный центр Бэйбилайф",
    city: "Алматы",
    address: "ул. Розыбакиева, 261",
    phone: "+7 (727) 393-30-30",
    workingHours: "Круглосуточно",
    sourceUrl: "https://beibalaife.kz",
    website: "https://beibalaife.kz",
    rating: 4.6,
    onlineBooking: true,
    lat: 43.218,
    lng: 76.892,
  },
  {
    sourceName: "Medison",
    clinicName: "Медицинский центр MEDISON",
    city: "Павлодар",
    address: "ул. Ленина, 56",
    phone: "+7 (7182) 33-44-55",
    workingHours: "Пн–Сб 08:00–19:00",
    sourceUrl: "https://medison.kz/pavlodar",
    website: "https://medison.kz",
    rating: 4.0,
    onlineBooking: false,
    lat: 52.287,
    lng: 76.97,
  },
  {
    sourceName: "Essen",
    clinicName: "Клиника Эссен",
    city: "Караганда",
    address: "ул. Алиханова, 12",
    phone: "+7 (7212) 44-55-66",
    workingHours: "Пн–Сб 08:00–20:00, Вс 09:00–14:00",
    sourceUrl: "https://essen-clinic.kz/karaganda",
    website: "https://essen-clinic.kz",
    rating: 4.2,
    onlineBooking: true,
    lat: 49.812,
    lng: 73.108,
  },
  {
    sourceName: "RakhatMed",
    clinicName: "Медицинский центр Рахат Мед",
    city: "Атырау",
    address: "пр. Казахстан, 38",
    phone: "+7 (7122) 60-70-80",
    workingHours: "Пн–Сб 08:00–20:00",
    sourceUrl: "https://rakhat-med.kz/atyrau",
    website: "https://rakhat-med.kz",
    rating: 4.1,
    onlineBooking: true,
    lat: 47.118,
    lng: 51.88,
  },
];

/** Base price ranges (KZT) per category for realistic generation. */
const BASE_PRICE: Record<ServiceCategory, [number, number]> = {
  laboratory: [1500, 18000],
  doctor_appointment: [5000, 25000],
  diagnostics: [4500, 65000],
  procedure: [2500, 22000],
};

/** Duration (days) baseline per category. */
const BASE_DURATION: Record<ServiceCategory, [number, number]> = {
  laboratory: [1, 5],
  doctor_appointment: [0, 1],
  diagnostics: [1, 3],
  procedure: [0, 1],
};

/**
 * For each clinic source, produce a list of raw price entries.
 * Each entry uses a RANDOM synonym variation of the service name so that
 * the normalization engine must unify "ОАК"/"CBC"/"Общий анализ крови" etc.
 * A few intentionally-unmappable names are injected to exercise the unmatched queue.
 */
export type RawPriceEntry = {
  serviceNameRaw: string;
  price: number;
  currency: "KZT" | "USD";
  durationDays: number;
  canonicalServiceIndex: number; // index into SERVICE_DIRECTORY_SEED
};

function pick<T>(arr: readonly T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

function jitter(base: number, pct: number): number {
  const delta = base * pct;
  return Math.round(base + (Math.random() * 2 - 1) * delta);
}

/**
 * Generate raw price entries for one clinic source.
 * Each clinic offers ~20-28 services drawn across categories.
 * Includes ~2 deliberately-unmappable raw names per clinic to feed the unmatched queue.
 */
export function generateRawEntriesForClinic(
  source: ClinicSourceDef,
  seed: number
): RawPriceEntry[] {
  // Deterministic pseudo-random based on seed for reproducibility
  let s = seed;
  const rand = () => {
    s = (s * 9301 + 49297) % 233280;
    return s / 233280;
  };
  const pickD = <T,>(arr: readonly T[]): T => arr[Math.floor(rand() * arr.length)];

  const entries: RawPriceEntry[] = [];
  const used = new Set<number>();

  // Each clinic covers a subset: all laboratory + a mix of others
  const indices = SERVICE_DIRECTORY_SEED.map((_, i) => i);
  // shuffle deterministically
  for (let i = indices.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [indices[i], indices[j]] = [indices[j], indices[i]];
  }
  const count = 20 + Math.floor(rand() * 9); // 20-28
  const selected = indices.slice(0, count);

  for (const idx of selected) {
    const svc = SERVICE_DIRECTORY_SEED[idx];
    // Use a random synonym OR the RU name to simulate raw scraped strings
    const variants = [svc.nameRu, ...svc.synonyms];
    const serviceNameRaw = pickD(variants);
    const [lo, hi] = BASE_PRICE[svc.category];
    const base = lo + rand() * (hi - lo);
    const price = Math.round(base / 50) * 50; // round to 50 KZT
    // NOTE: All seeded prices are in KZT. Earlier versions mislabeled ~8% as USD,
    // which caused the scraper's `toKzt(price, "USD") = price * 470` to inflate
    // those entries by 470× (e.g. ₸35,250 → ₸16,567,500). Keep currency="KZT"
    // here; real USD listings would only come from actual scrapers.
    const currency: "KZT" | "USD" = "KZT";
    const [dlo, dhi] = BASE_DURATION[svc.category];
    const durationDays = Math.floor(dlo + rand() * (dhi - dlo + 1));
    entries.push({ serviceNameRaw, price, currency, durationDays, canonicalServiceIndex: idx });
    used.add(idx);
  }

  // Inject 1-2 deliberately unmappable entries (random generic strings)
  const garbage = [
    "Комплексная диагностика организма премиум",
    "Специальное предложение сезона",
    "Уникальная процедура омоложения",
    "Расширенный чекап VIP",
  ];
  const gCount = 1 + Math.floor(rand() * 2);
  for (let i = 0; i < gCount; i++) {
    entries.push({
      serviceNameRaw: pickD(garbage),
      price: Math.round((8000 + rand() * 40000) / 50) * 50,
      currency: "KZT",
      durationDays: 1 + Math.floor(rand() * 3),
      canonicalServiceIndex: -1, // signals unmappable
    });
  }

  return entries;
}

/** Approximate USD->KZT rate (would normally come from a live FX feed). */
export const USD_TO_KZT_RATE = 470;
