/**
 * POST /api/v1/ai/search
 * Natural-language medical service search.
 *
 * Users describe what they need in plain language (RU/EN/KK) and the LLM maps
 * the description to relevant services from the service directory.
 *
 * Body:  { "query": "I need a full health checkup with blood work and thyroid tests" }
 * Response:
 * {
 *   "query": "...",
 *   "services": [
 *     { "id","nameRu","nameKk","nameEn","category","synonyms",
 *       "aiReason":"...","aiScore":0.95 }, ...
 *   ],
 *   "elapsedMs": 1834,
 *   "warning": "..." // only present when the LLM response could not be parsed
 * }
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * SAFETY GUARDRAILS (critical — directive: "The AI must not generate fake
 * medical advice or invent pricing data"):
 *
 * 1. The LLM is constrained by the system prompt to ONLY select services whose
 *    IDs appear in the provided service directory. It may not invent services.
 * 2. After the LLM responds, every returned ID is verified by lookup in the
 *    freshly-loaded directory. Any hallucinated / unknown IDs are dropped
 *    (see "guardrail #2" below). The response therefore contains ONLY real
 *    directory services — never LLM-fabricated records.
 * 3. No medical advice is generated. The only LLM-produced text that reaches
 *    the user is the short `aiReason` string, which describes WHY a known
 *    directory service matches the query — not what the user should do.
 * 4. No pricing data is generated by the AI. Prices are never returned by this
 *    endpoint at all (it only returns directory metadata); prices elsewhere in
 *    the platform come exclusively from the database via the normalization
 *    pipeline, never from the LLM.
 * 5. `max_tokens` is capped on the LLM call to bound response size and prevent
 *    runaway output.
 * ─────────────────────────────────────────────────────────────────────────────
 */
import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import ZAI from "z-ai-web-dev-sdk";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// Bounds
const MIN_QUERY_LEN = 3;
const MAX_QUERY_LEN = 500;
const MAX_MATCHES = 8; // upper bound on returned services
const MAX_TOKENS = 1200; // cap LLM response to avoid runaway output

type LLMMatch = {
  id?: string;
  score?: number;
  reason?: string;
};

type ServiceHit = {
  id: string;
  nameRu: string;
  nameKk: string;
  nameEn: string;
  category: string;
  synonyms: string[];
  aiReason: string;
  aiScore: number;
};

/** Parse the `synonyms` JSON-string column into a string[] (defensive). */
function safeSynonyms(s: string | null | undefined): string[] {
  if (!s) return [];
  try {
    const v = JSON.parse(s);
    return Array.isArray(v) ? v.map((x) => String(x)) : [];
  } catch {
    return [];
  }
}

export async function POST(req: NextRequest) {
  const t0 = Date.now();

  // ── 1. Parse + validate body ──────────────────────────────────────────────
  let body: { query?: unknown } = {};
  try {
    body = await req.json();
  } catch {
    return NextResponse.json(
      { error: "Invalid JSON body" },
      { status: 400 }
    );
  }

  const query = typeof body.query === "string" ? body.query.trim() : "";

  if (query.length < MIN_QUERY_LEN || query.length > MAX_QUERY_LEN) {
    return NextResponse.json(
      {
        error: `Query must be a non-empty string between ${MIN_QUERY_LEN} and ${MAX_QUERY_LEN} characters`,
      },
      { status: 400 }
    );
  }

  // ── 2. Load full service directory ────────────────────────────────────────
  let directory: Array<{
    id: string;
    nameRu: string;
    nameKk: string;
    nameEn: string;
    category: string;
    synonyms: string[];
  }>;
  try {
    const rows = await db.serviceDirectory.findMany({
      select: {
        id: true,
        nameRu: true,
        nameKk: true,
        nameEn: true,
        category: true,
        synonyms: true,
      },
      orderBy: { category: "asc" },
    });
    directory = rows.map((r) => ({
      id: r.id,
      nameRu: r.nameRu,
      nameKk: r.nameKk,
      nameEn: r.nameEn,
      category: r.category,
      synonyms: safeSynonyms(r.synonyms),
    }));
  } catch (e) {
    return NextResponse.json(
      { error: "Failed to load service directory", detail: String((e as Error).message) },
      { status: 500 }
    );
  }

  if (!directory.length) {
    return NextResponse.json(
      {
        query,
        services: [],
        elapsedMs: Date.now() - t0,
        warning: "Service directory is empty",
      },
      { status: 200 }
    );
  }

  // ── 3. Build compact directory context for the LLM ────────────────────────
  // Format: [ID: <id>] <nameRu> / <nameKk> / <nameEn> (<category>) — synonyms: a, b, c
  // ~80 chars/service × 120 services ≈ ~10KB — well within LLM context.
  const directoryContext = directory
    .map((d) => {
      const syn = d.synonyms.slice(0, 3).join(", ");
      return `[ID: ${d.id}] ${d.nameRu} / ${d.nameKk} / ${d.nameEn} (${d.category})${syn ? ` — synonyms: ${syn}` : ""}`;
    })
    .join("\n");

  // ── 4. System prompt (guardrails #1, #3) ──────────────────────────────────
  const systemPrompt = `You are a medical service matching assistant for a Kazakhstan medical price comparison platform.
The user will describe what they need in natural language (Russian, English, or Kazakh).
Match their request to the most relevant services from the provided service directory.

Return a JSON array of up to ${MAX_MATCHES} matches, each with:
- "id": the service ID from the directory (exactly as given, e.g. "svc_001")
- "score": relevance score 0.0-1.0
- "reason": a brief explanation in the user's language of WHY this service matches the request

STRICT RULES:
- You may ONLY select services whose IDs appear in the directory below. NEVER invent or fabricate service IDs or names.
- Only include services that are genuinely relevant to the user's request. If fewer than ${MAX_MATCHES} are relevant, return fewer.
- If none of the directory services are relevant, return an empty array [].
- The "reason" must describe why the service matches — it must NOT give medical advice, diagnosis, or treatment recommendations.
- Do NOT mention prices; pricing is not part of this task.

Respond ONLY with the JSON array. No markdown, no code fences, no commentary.`;

  const userPrompt = `SERVICE DIRECTORY:\n${directoryContext}\n\nUSER REQUEST:\n${query}\n\nReturn the JSON array now.`;

  // ── 5. Call the LLM ───────────────────────────────────────────────────────
  let aiResponse = "";
  try {
    const zai = await ZAI.create();
    const completion = await zai.chat.completions.create({
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      temperature: 0.2, // deterministic-ish matching
      max_tokens: MAX_TOKENS,
      thinking: { type: "disabled" },
    });
    aiResponse = completion.choices[0]?.message?.content ?? "";
  } catch (e) {
    return NextResponse.json(
      {
        error: "LLM call failed",
        detail: String((e as Error).message),
        elapsedMs: Date.now() - t0,
      },
      { status: 502 }
    );
  }

  // ── 6. Parse the LLM JSON array (graceful — never crash) ──────────────────
  let parsed: LLMMatch[] = [];
  let warning: string | undefined;

  const cleaned = aiResponse
    .replace(/```json\s*/gi, "")
    .replace(/```\s*/g, "")
    .trim();

  try {
    const start = cleaned.indexOf("[");
    const end = cleaned.lastIndexOf("]");
    if (start >= 0 && end > start) {
      const candidate = JSON.parse(cleaned.slice(start, end + 1));
      if (Array.isArray(candidate)) {
        parsed = candidate as LLMMatch[];
      } else {
        warning = "LLM response was valid JSON but not an array";
      }
    } else {
      warning = "LLM response did not contain a JSON array";
    }
  } catch (e) {
    warning = `Failed to parse LLM JSON: ${String((e as Error).message)}`;
  }

  // ── 7. Map LLM matches → full directory records (guardrail #2: ID verify) ─
  const byId = new Map(directory.map((d) => [d.id, d]));
  const seen = new Set<string>();
  const hits: ServiceHit[] = [];

  for (const m of parsed) {
    const id = typeof m?.id === "string" ? m.id.trim() : "";
    if (!id || seen.has(id)) continue;

    const svc = byId.get(id);
    if (!svc) {
      // LLM hallucinated / returned a non-existent ID — drop it (guardrail #2).
      continue;
    }

    seen.add(id);

    // Sanitize + clamp score to [0,1]
    const rawScore = Number(m.score);
    const aiScore = Number.isFinite(rawScore)
      ? Math.max(0, Math.min(1, rawScore))
      : 0;

    // Sanitize reason (cap length, strip newlines)
    const aiReason = String(m.reason ?? "")
      .replace(/[\r\n]+/g, " ")
      .trim()
      .slice(0, 400);

    hits.push({
      id: svc.id,
      nameRu: svc.nameRu,
      nameKk: svc.nameKk,
      nameEn: svc.nameEn,
      category: svc.category,
      synonyms: svc.synonyms,
      aiReason,
      aiScore,
    });
  }

  // ── 8-9. Cap at MAX_MATCHES and sort by score desc ────────────────────────
  hits.sort((a, b) => b.aiScore - a.aiScore);
  const top = hits.slice(0, MAX_MATCHES);

  // ── 10. Return response with elapsedMs ────────────────────────────────────
  const responseBody: Record<string, unknown> = {
    query,
    services: top,
    elapsedMs: Date.now() - t0,
  };
  if (warning) responseBody.warning = warning;

  return NextResponse.json(responseBody, { status: 200 });
}
